// Code generated by testify/internal/testifygen; DO NOT EDIT.

package require

import (
	http "net/http"
	url "net/url"
	time "time"

	assert "github.com/allure-framework/allure-go/testify/assert"
	report "github.com/allure-framework/allure-go/testify/internal/report"
	upstream "github.com/stretchr/testify/require"
)

// Condition uses a Comparison to assert a complex condition.
func Condition(t TestingT, comp assert.Comparison, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Condition")
	call.Capture(report.Arg("comp", comp))
	defer call.FinishRequire()
	upstream.Condition(call.RequireT(), comp, msgAndArgs...)
}

// Conditionf uses a Comparison to assert a complex condition.
func Conditionf(t TestingT, comp assert.Comparison, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Conditionf")
	call.Capture(report.Arg("comp", comp))
	defer call.FinishRequire()
	upstream.Conditionf(call.RequireT(), comp, msg, args...)
}

// Contains asserts that the specified string, list(array, slice...) or map contains the
// specified substring or element.
//
//	require.Contains(t, "Hello World", "World")
//	require.Contains(t, ["Hello", "World"], "World")
//	require.Contains(t, {"Hello": "World"}, "Hello")
func Contains(t TestingT, s interface{}, contains interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Contains")
	call.Capture(report.Arg("s", s), report.Arg("contains", contains))
	defer call.FinishRequire()
	upstream.Contains(call.RequireT(), s, contains, msgAndArgs...)
}

// Containsf asserts that the specified string, list(array, slice...) or map contains the
// specified substring or element.
//
//	require.Containsf(t, "Hello World", "World", "error message %s", "formatted")
//	require.Containsf(t, ["Hello", "World"], "World", "error message %s", "formatted")
//	require.Containsf(t, {"Hello": "World"}, "Hello", "error message %s", "formatted")
func Containsf(t TestingT, s interface{}, contains interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Containsf")
	call.Capture(report.Arg("s", s), report.Arg("contains", contains))
	defer call.FinishRequire()
	upstream.Containsf(call.RequireT(), s, contains, msg, args...)
}

// DirExists checks whether a directory exists in the given path. It also fails
// if the path is a file rather a directory or there is an error checking whether it exists.
func DirExists(t TestingT, path string, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.DirExists")
	call.Capture(report.Arg("path", path))
	defer call.FinishRequire()
	upstream.DirExists(call.RequireT(), path, msgAndArgs...)
}

// DirExistsf checks whether a directory exists in the given path. It also fails
// if the path is a file rather a directory or there is an error checking whether it exists.
func DirExistsf(t TestingT, path string, msg string, args ...interface{}) {
	call := report.Begin(t, "require.DirExistsf")
	call.Capture(report.Arg("path", path))
	defer call.FinishRequire()
	upstream.DirExistsf(call.RequireT(), path, msg, args...)
}

// ElementsMatch asserts that the specified listA(array, slice...) is equal to specified
// listB(array, slice...) ignoring the order of the elements. If there are duplicate elements,
// the number of appearances of each of them in both lists should match.
//
// require.ElementsMatch(t, [1, 3, 2, 3], [1, 3, 3, 2])
func ElementsMatch(t TestingT, listA interface{}, listB interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.ElementsMatch")
	call.Capture(report.Arg("listA", listA), report.Arg("listB", listB))
	defer call.FinishRequire()
	upstream.ElementsMatch(call.RequireT(), listA, listB, msgAndArgs...)
}

// ElementsMatchf asserts that the specified listA(array, slice...) is equal to specified
// listB(array, slice...) ignoring the order of the elements. If there are duplicate elements,
// the number of appearances of each of them in both lists should match.
//
// require.ElementsMatchf(t, [1, 3, 2, 3], [1, 3, 3, 2], "error message %s", "formatted")
func ElementsMatchf(t TestingT, listA interface{}, listB interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.ElementsMatchf")
	call.Capture(report.Arg("listA", listA), report.Arg("listB", listB))
	defer call.FinishRequire()
	upstream.ElementsMatchf(call.RequireT(), listA, listB, msg, args...)
}

// Empty asserts that the given value is "empty".
//
// [Zero values] are "empty".
//
// Arrays are "empty" if every element is the zero value of the type (stricter than "empty").
//
// Slices, maps and channels with zero length are "empty".
//
// Pointer values are "empty" if the pointer is nil or if the pointed value is "empty".
//
//	require.Empty(t, obj)
//
// [Zero values]: https://go.dev/ref/spec#The_zero_value
func Empty(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Empty")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.Empty(call.RequireT(), object, msgAndArgs...)
}

// Emptyf asserts that the given value is "empty".
//
// [Zero values] are "empty".
//
// Arrays are "empty" if every element is the zero value of the type (stricter than "empty").
//
// Slices, maps and channels with zero length are "empty".
//
// Pointer values are "empty" if the pointer is nil or if the pointed value is "empty".
//
//	require.Emptyf(t, obj, "error message %s", "formatted")
//
// [Zero values]: https://go.dev/ref/spec#The_zero_value
func Emptyf(t TestingT, object interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Emptyf")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.Emptyf(call.RequireT(), object, msg, args...)
}

// Equal asserts that two objects are equal.
//
//	require.Equal(t, 123, 123)
//
// Pointer variable equality is determined based on the equality of the
// referenced values (as opposed to the memory addresses). Function equality
// cannot be determined and will always fail.
func Equal(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Equal")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.Equal(call.RequireT(), expected, actual, msgAndArgs...)
}

// EqualError asserts that a function returned an error (i.e. not `nil`)
// and that it is equal to the provided error.
//
//	actualObj, err := SomeFunction()
//	require.EqualError(t, err,  expectedErrorString)
func EqualError(t TestingT, theError error, errString string, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.EqualError")
	call.Capture(report.Arg("theError", theError), report.Arg("errString", errString))
	defer call.FinishRequire()
	upstream.EqualError(call.RequireT(), theError, errString, msgAndArgs...)
}

// EqualErrorf asserts that a function returned an error (i.e. not `nil`)
// and that it is equal to the provided error.
//
//	actualObj, err := SomeFunction()
//	require.EqualErrorf(t, err,  expectedErrorString, "error message %s", "formatted")
func EqualErrorf(t TestingT, theError error, errString string, msg string, args ...interface{}) {
	call := report.Begin(t, "require.EqualErrorf")
	call.Capture(report.Arg("theError", theError), report.Arg("errString", errString))
	defer call.FinishRequire()
	upstream.EqualErrorf(call.RequireT(), theError, errString, msg, args...)
}

// EqualExportedValues asserts that the types of two objects are equal and their public
// fields are also equal. This is useful for comparing structs that have private fields
// that could potentially differ.
//
//	 type S struct {
//		Exported     	int
//		notExported   	int
//	 }
//	 require.EqualExportedValues(t, S{1, 2}, S{1, 3}) => true
//	 require.EqualExportedValues(t, S{1, 2}, S{2, 3}) => false
func EqualExportedValues(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.EqualExportedValues")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.EqualExportedValues(call.RequireT(), expected, actual, msgAndArgs...)
}

// EqualExportedValuesf asserts that the types of two objects are equal and their public
// fields are also equal. This is useful for comparing structs that have private fields
// that could potentially differ.
//
//	 type S struct {
//		Exported     	int
//		notExported   	int
//	 }
//	 require.EqualExportedValuesf(t, S{1, 2}, S{1, 3}, "error message %s", "formatted") => true
//	 require.EqualExportedValuesf(t, S{1, 2}, S{2, 3}, "error message %s", "formatted") => false
func EqualExportedValuesf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.EqualExportedValuesf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.EqualExportedValuesf(call.RequireT(), expected, actual, msg, args...)
}

// EqualValues asserts that two objects are equal or convertible to the larger
// type and equal.
//
//	require.EqualValues(t, uint32(123), int32(123))
func EqualValues(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.EqualValues")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.EqualValues(call.RequireT(), expected, actual, msgAndArgs...)
}

// EqualValuesf asserts that two objects are equal or convertible to the larger
// type and equal.
//
//	require.EqualValuesf(t, uint32(123), int32(123), "error message %s", "formatted")
func EqualValuesf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.EqualValuesf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.EqualValuesf(call.RequireT(), expected, actual, msg, args...)
}

// Equalf asserts that two objects are equal.
//
//	require.Equalf(t, 123, 123, "error message %s", "formatted")
//
// Pointer variable equality is determined based on the equality of the
// referenced values (as opposed to the memory addresses). Function equality
// cannot be determined and will always fail.
func Equalf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Equalf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.Equalf(call.RequireT(), expected, actual, msg, args...)
}

// Error asserts that a function returned an error (i.e. not `nil`).
//
//	actualObj, err := SomeFunction()
//	require.Error(t, err)
func Error(t TestingT, err error, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Error")
	call.Capture(report.Arg("err", err))
	defer call.FinishRequire()
	upstream.Error(call.RequireT(), err, msgAndArgs...)
}

// ErrorAs asserts that at least one of the errors in err's chain matches target, and if so, sets target to that error value.
// This is a wrapper for errors.As.
func ErrorAs(t TestingT, err error, target interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.ErrorAs")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	defer call.FinishRequire()
	upstream.ErrorAs(call.RequireT(), err, target, msgAndArgs...)
}

// ErrorAsf asserts that at least one of the errors in err's chain matches target, and if so, sets target to that error value.
// This is a wrapper for errors.As.
func ErrorAsf(t TestingT, err error, target interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.ErrorAsf")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	defer call.FinishRequire()
	upstream.ErrorAsf(call.RequireT(), err, target, msg, args...)
}

// ErrorContains asserts that a function returned an error (i.e. not `nil`)
// and that the error contains the specified substring.
//
//	actualObj, err := SomeFunction()
//	require.ErrorContains(t, err,  expectedErrorSubString)
func ErrorContains(t TestingT, theError error, contains string, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.ErrorContains")
	call.Capture(report.Arg("theError", theError), report.Arg("contains", contains))
	defer call.FinishRequire()
	upstream.ErrorContains(call.RequireT(), theError, contains, msgAndArgs...)
}

// ErrorContainsf asserts that a function returned an error (i.e. not `nil`)
// and that the error contains the specified substring.
//
//	actualObj, err := SomeFunction()
//	require.ErrorContainsf(t, err,  expectedErrorSubString, "error message %s", "formatted")
func ErrorContainsf(t TestingT, theError error, contains string, msg string, args ...interface{}) {
	call := report.Begin(t, "require.ErrorContainsf")
	call.Capture(report.Arg("theError", theError), report.Arg("contains", contains))
	defer call.FinishRequire()
	upstream.ErrorContainsf(call.RequireT(), theError, contains, msg, args...)
}

// ErrorIs asserts that at least one of the errors in err's chain matches target.
// This is a wrapper for errors.Is.
func ErrorIs(t TestingT, err error, target error, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.ErrorIs")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	defer call.FinishRequire()
	upstream.ErrorIs(call.RequireT(), err, target, msgAndArgs...)
}

// ErrorIsf asserts that at least one of the errors in err's chain matches target.
// This is a wrapper for errors.Is.
func ErrorIsf(t TestingT, err error, target error, msg string, args ...interface{}) {
	call := report.Begin(t, "require.ErrorIsf")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	defer call.FinishRequire()
	upstream.ErrorIsf(call.RequireT(), err, target, msg, args...)
}

// Errorf asserts that a function returned an error (i.e. not `nil`).
//
//	actualObj, err := SomeFunction()
//	require.Errorf(t, err, "error message %s", "formatted")
func Errorf(t TestingT, err error, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Errorf")
	call.Capture(report.Arg("err", err))
	defer call.FinishRequire()
	upstream.Errorf(call.RequireT(), err, msg, args...)
}

// Eventually asserts that given condition will be met in waitFor time,
// periodically checking target function each tick.
//
//	require.Eventually(t, func() bool { return true; }, time.Second, 10*time.Millisecond)
func Eventually(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Eventually")
	call.Capture(report.Arg("condition", condition), report.Arg("waitFor", waitFor), report.Arg("tick", tick))
	defer call.FinishRequire()
	upstream.Eventually(call.RequireT(), condition, waitFor, tick, msgAndArgs...)
}

// EventuallyWithT asserts that given condition will be met in waitFor time,
// periodically checking target function each tick. In contrast to Eventually,
// it supplies a CollectT to the condition function, so that the condition
// function can use the CollectT to call other assertions.
// The condition is considered "met" if no errors are raised in a tick.
// The supplied CollectT collects all errors from one tick (if there are any).
// If the condition is not met before waitFor, the collected errors of
// the last tick are copied to t.
//
//	externalValue := false
//	go func() {
//		time.Sleep(8*time.Second)
//		externalValue = true
//	}()
//	require.EventuallyWithT(t, func(c *require.CollectT) {
//		// add assertions as needed; any assertion failure will fail the current tick
//		require.True(c, externalValue, "expected 'externalValue' to be true")
//	}, 10*time.Second, 1*time.Second, "external state has not changed to 'true'; still false")
func EventuallyWithT(t TestingT, condition func(collect *assert.CollectT), waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.EventuallyWithT")
	call.Capture(report.Arg("condition", condition), report.Arg("waitFor", waitFor), report.Arg("tick", tick))
	defer call.FinishRequire()
	upstream.EventuallyWithT(call.RequireT(), condition, waitFor, tick, msgAndArgs...)
}

// EventuallyWithTf asserts that given condition will be met in waitFor time,
// periodically checking target function each tick. In contrast to Eventually,
// it supplies a CollectT to the condition function, so that the condition
// function can use the CollectT to call other assertions.
// The condition is considered "met" if no errors are raised in a tick.
// The supplied CollectT collects all errors from one tick (if there are any).
// If the condition is not met before waitFor, the collected errors of
// the last tick are copied to t.
//
//	externalValue := false
//	go func() {
//		time.Sleep(8*time.Second)
//		externalValue = true
//	}()
//	require.EventuallyWithTf(t, func(c *require.CollectT, "error message %s", "formatted") {
//		// add assertions as needed; any assertion failure will fail the current tick
//		require.True(c, externalValue, "expected 'externalValue' to be true")
//	}, 10*time.Second, 1*time.Second, "external state has not changed to 'true'; still false")
func EventuallyWithTf(t TestingT, condition func(collect *assert.CollectT), waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) {
	call := report.Begin(t, "require.EventuallyWithTf")
	call.Capture(report.Arg("condition", condition), report.Arg("waitFor", waitFor), report.Arg("tick", tick))
	defer call.FinishRequire()
	upstream.EventuallyWithTf(call.RequireT(), condition, waitFor, tick, msg, args...)
}

// Eventuallyf asserts that given condition will be met in waitFor time,
// periodically checking target function each tick.
//
//	require.Eventuallyf(t, func() bool { return true; }, time.Second, 10*time.Millisecond, "error message %s", "formatted")
func Eventuallyf(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Eventuallyf")
	call.Capture(report.Arg("condition", condition), report.Arg("waitFor", waitFor), report.Arg("tick", tick))
	defer call.FinishRequire()
	upstream.Eventuallyf(call.RequireT(), condition, waitFor, tick, msg, args...)
}

// Exactly asserts that two objects are equal in value and type.
//
//	require.Exactly(t, int32(123), int64(123))
func Exactly(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Exactly")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.Exactly(call.RequireT(), expected, actual, msgAndArgs...)
}

// Exactlyf asserts that two objects are equal in value and type.
//
//	require.Exactlyf(t, int32(123), int64(123), "error message %s", "formatted")
func Exactlyf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Exactlyf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.Exactlyf(call.RequireT(), expected, actual, msg, args...)
}

// Fail reports a failure through
func Fail(t TestingT, failureMessage string, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Fail")
	call.Capture(report.Arg("failureMessage", failureMessage))
	defer call.FinishRequire()
	upstream.Fail(call.RequireT(), failureMessage, msgAndArgs...)
}

// FailNow fails test
func FailNow(t TestingT, failureMessage string, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.FailNow")
	call.Capture(report.Arg("failureMessage", failureMessage))
	defer call.FinishRequire()
	upstream.FailNow(call.RequireT(), failureMessage, msgAndArgs...)
}

// FailNowf fails test
func FailNowf(t TestingT, failureMessage string, msg string, args ...interface{}) {
	call := report.Begin(t, "require.FailNowf")
	call.Capture(report.Arg("failureMessage", failureMessage))
	defer call.FinishRequire()
	upstream.FailNowf(call.RequireT(), failureMessage, msg, args...)
}

// Failf reports a failure through
func Failf(t TestingT, failureMessage string, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Failf")
	call.Capture(report.Arg("failureMessage", failureMessage))
	defer call.FinishRequire()
	upstream.Failf(call.RequireT(), failureMessage, msg, args...)
}

// False asserts that the specified value is false.
//
//	require.False(t, myBool)
func False(t TestingT, value bool, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.False")
	call.Capture(report.Arg("value", value))
	defer call.FinishRequire()
	upstream.False(call.RequireT(), value, msgAndArgs...)
}

// Falsef asserts that the specified value is false.
//
//	require.Falsef(t, myBool, "error message %s", "formatted")
func Falsef(t TestingT, value bool, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Falsef")
	call.Capture(report.Arg("value", value))
	defer call.FinishRequire()
	upstream.Falsef(call.RequireT(), value, msg, args...)
}

// FileExists checks whether a file exists in the given path. It also fails if
// the path points to a directory or there is an error when trying to check the file.
func FileExists(t TestingT, path string, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.FileExists")
	call.Capture(report.Arg("path", path))
	defer call.FinishRequire()
	upstream.FileExists(call.RequireT(), path, msgAndArgs...)
}

// FileExistsf checks whether a file exists in the given path. It also fails if
// the path points to a directory or there is an error when trying to check the file.
func FileExistsf(t TestingT, path string, msg string, args ...interface{}) {
	call := report.Begin(t, "require.FileExistsf")
	call.Capture(report.Arg("path", path))
	defer call.FinishRequire()
	upstream.FileExistsf(call.RequireT(), path, msg, args...)
}

// Greater asserts that the first element is greater than the second
//
//	require.Greater(t, 2, 1)
//	require.Greater(t, float64(2), float64(1))
//	require.Greater(t, "b", "a")
func Greater(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Greater")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	defer call.FinishRequire()
	upstream.Greater(call.RequireT(), e1, e2, msgAndArgs...)
}

// GreaterOrEqual asserts that the first element is greater than or equal to the second
//
//	require.GreaterOrEqual(t, 2, 1)
//	require.GreaterOrEqual(t, 2, 2)
//	require.GreaterOrEqual(t, "b", "a")
//	require.GreaterOrEqual(t, "b", "b")
func GreaterOrEqual(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.GreaterOrEqual")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	defer call.FinishRequire()
	upstream.GreaterOrEqual(call.RequireT(), e1, e2, msgAndArgs...)
}

// GreaterOrEqualf asserts that the first element is greater than or equal to the second
//
//	require.GreaterOrEqualf(t, 2, 1, "error message %s", "formatted")
//	require.GreaterOrEqualf(t, 2, 2, "error message %s", "formatted")
//	require.GreaterOrEqualf(t, "b", "a", "error message %s", "formatted")
//	require.GreaterOrEqualf(t, "b", "b", "error message %s", "formatted")
func GreaterOrEqualf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.GreaterOrEqualf")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	defer call.FinishRequire()
	upstream.GreaterOrEqualf(call.RequireT(), e1, e2, msg, args...)
}

// Greaterf asserts that the first element is greater than the second
//
//	require.Greaterf(t, 2, 1, "error message %s", "formatted")
//	require.Greaterf(t, float64(2), float64(1), "error message %s", "formatted")
//	require.Greaterf(t, "b", "a", "error message %s", "formatted")
func Greaterf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Greaterf")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	defer call.FinishRequire()
	upstream.Greaterf(call.RequireT(), e1, e2, msg, args...)
}

// HTTPBodyContains asserts that a specified handler returns a
// body that contains a string.
//
//	require.HTTPBodyContains(t, myHandler, "GET", "www.google.com", nil, "I'm Feeling Lucky")
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPBodyContains(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.HTTPBodyContains")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values), report.Arg("str", str))
	defer call.FinishRequire()
	upstream.HTTPBodyContains(call.RequireT(), handler, method, url, values, str, msgAndArgs...)
}

// HTTPBodyContainsf asserts that a specified handler returns a
// body that contains a string.
//
//	require.HTTPBodyContainsf(t, myHandler, "GET", "www.google.com", nil, "I'm Feeling Lucky", "error message %s", "formatted")
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPBodyContainsf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.HTTPBodyContainsf")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values), report.Arg("str", str))
	defer call.FinishRequire()
	upstream.HTTPBodyContainsf(call.RequireT(), handler, method, url, values, str, msg, args...)
}

// HTTPBodyNotContains asserts that a specified handler returns a
// body that does not contain a string.
//
//	require.HTTPBodyNotContains(t, myHandler, "GET", "www.google.com", nil, "I'm Feeling Lucky")
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPBodyNotContains(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.HTTPBodyNotContains")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values), report.Arg("str", str))
	defer call.FinishRequire()
	upstream.HTTPBodyNotContains(call.RequireT(), handler, method, url, values, str, msgAndArgs...)
}

// HTTPBodyNotContainsf asserts that a specified handler returns a
// body that does not contain a string.
//
//	require.HTTPBodyNotContainsf(t, myHandler, "GET", "www.google.com", nil, "I'm Feeling Lucky", "error message %s", "formatted")
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPBodyNotContainsf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.HTTPBodyNotContainsf")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values), report.Arg("str", str))
	defer call.FinishRequire()
	upstream.HTTPBodyNotContainsf(call.RequireT(), handler, method, url, values, str, msg, args...)
}

// HTTPError asserts that a specified handler returns an error status code.
//
//	require.HTTPError(t, myHandler, "POST", "/a/b/c", url.Values{"a": []string{"b", "c"}}
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPError(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.HTTPError")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values))
	defer call.FinishRequire()
	upstream.HTTPError(call.RequireT(), handler, method, url, values, msgAndArgs...)
}

// HTTPErrorf asserts that a specified handler returns an error status code.
//
//	require.HTTPErrorf(t, myHandler, "POST", "/a/b/c", url.Values{"a": []string{"b", "c"}}
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPErrorf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) {
	call := report.Begin(t, "require.HTTPErrorf")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values))
	defer call.FinishRequire()
	upstream.HTTPErrorf(call.RequireT(), handler, method, url, values, msg, args...)
}

// HTTPRedirect asserts that a specified handler returns a redirect status code.
//
//	require.HTTPRedirect(t, myHandler, "GET", "/a/b/c", url.Values{"a": []string{"b", "c"}}
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPRedirect(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.HTTPRedirect")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values))
	defer call.FinishRequire()
	upstream.HTTPRedirect(call.RequireT(), handler, method, url, values, msgAndArgs...)
}

// HTTPRedirectf asserts that a specified handler returns a redirect status code.
//
//	require.HTTPRedirectf(t, myHandler, "GET", "/a/b/c", url.Values{"a": []string{"b", "c"}}
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPRedirectf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) {
	call := report.Begin(t, "require.HTTPRedirectf")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values))
	defer call.FinishRequire()
	upstream.HTTPRedirectf(call.RequireT(), handler, method, url, values, msg, args...)
}

// HTTPStatusCode asserts that a specified handler returns a specified status code.
//
//	require.HTTPStatusCode(t, myHandler, "GET", "/notImplemented", nil, 501)
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPStatusCode(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, statuscode int, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.HTTPStatusCode")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values), report.Arg("statuscode", statuscode))
	defer call.FinishRequire()
	upstream.HTTPStatusCode(call.RequireT(), handler, method, url, values, statuscode, msgAndArgs...)
}

// HTTPStatusCodef asserts that a specified handler returns a specified status code.
//
//	require.HTTPStatusCodef(t, myHandler, "GET", "/notImplemented", nil, 501, "error message %s", "formatted")
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPStatusCodef(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, statuscode int, msg string, args ...interface{}) {
	call := report.Begin(t, "require.HTTPStatusCodef")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values), report.Arg("statuscode", statuscode))
	defer call.FinishRequire()
	upstream.HTTPStatusCodef(call.RequireT(), handler, method, url, values, statuscode, msg, args...)
}

// HTTPSuccess asserts that a specified handler returns a success status code.
//
//	require.HTTPSuccess(t, myHandler, "POST", "http://www.google.com", nil)
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPSuccess(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.HTTPSuccess")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values))
	defer call.FinishRequire()
	upstream.HTTPSuccess(call.RequireT(), handler, method, url, values, msgAndArgs...)
}

// HTTPSuccessf asserts that a specified handler returns a success status code.
//
//	require.HTTPSuccessf(t, myHandler, "POST", "http://www.google.com", nil, "error message %s", "formatted")
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPSuccessf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) {
	call := report.Begin(t, "require.HTTPSuccessf")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values))
	defer call.FinishRequire()
	upstream.HTTPSuccessf(call.RequireT(), handler, method, url, values, msg, args...)
}

// Implements asserts that an object is implemented by the specified interface.
//
//	require.Implements(t, (*MyInterface)(nil), new(MyObject))
func Implements(t TestingT, interfaceObject interface{}, object interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Implements")
	call.Capture(report.Arg("interfaceObject", interfaceObject), report.Arg("object", object))
	defer call.FinishRequire()
	upstream.Implements(call.RequireT(), interfaceObject, object, msgAndArgs...)
}

// Implementsf asserts that an object is implemented by the specified interface.
//
//	require.Implementsf(t, (*MyInterface)(nil), new(MyObject), "error message %s", "formatted")
func Implementsf(t TestingT, interfaceObject interface{}, object interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Implementsf")
	call.Capture(report.Arg("interfaceObject", interfaceObject), report.Arg("object", object))
	defer call.FinishRequire()
	upstream.Implementsf(call.RequireT(), interfaceObject, object, msg, args...)
}

// InDelta asserts that the two numerals are within delta of each other.
//
//	require.InDelta(t, math.Pi, 22/7.0, 0.01)
func InDelta(t TestingT, expected interface{}, actual interface{}, delta float64, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.InDelta")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	defer call.FinishRequire()
	upstream.InDelta(call.RequireT(), expected, actual, delta, msgAndArgs...)
}

// InDeltaMapValues is the same as InDelta, but it compares all values between two maps. Both maps must have exactly the same keys.
func InDeltaMapValues(t TestingT, expected interface{}, actual interface{}, delta float64, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.InDeltaMapValues")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	defer call.FinishRequire()
	upstream.InDeltaMapValues(call.RequireT(), expected, actual, delta, msgAndArgs...)
}

// InDeltaMapValuesf is the same as InDelta, but it compares all values between two maps. Both maps must have exactly the same keys.
func InDeltaMapValuesf(t TestingT, expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) {
	call := report.Begin(t, "require.InDeltaMapValuesf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	defer call.FinishRequire()
	upstream.InDeltaMapValuesf(call.RequireT(), expected, actual, delta, msg, args...)
}

// InDeltaSlice is the same as InDelta, except it compares two slices.
func InDeltaSlice(t TestingT, expected interface{}, actual interface{}, delta float64, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.InDeltaSlice")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	defer call.FinishRequire()
	upstream.InDeltaSlice(call.RequireT(), expected, actual, delta, msgAndArgs...)
}

// InDeltaSlicef is the same as InDelta, except it compares two slices.
func InDeltaSlicef(t TestingT, expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) {
	call := report.Begin(t, "require.InDeltaSlicef")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	defer call.FinishRequire()
	upstream.InDeltaSlicef(call.RequireT(), expected, actual, delta, msg, args...)
}

// InDeltaf asserts that the two numerals are within delta of each other.
//
//	require.InDeltaf(t, math.Pi, 22/7.0, 0.01, "error message %s", "formatted")
func InDeltaf(t TestingT, expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) {
	call := report.Begin(t, "require.InDeltaf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	defer call.FinishRequire()
	upstream.InDeltaf(call.RequireT(), expected, actual, delta, msg, args...)
}

// InEpsilon asserts that expected and actual have a relative error less than epsilon
func InEpsilon(t TestingT, expected interface{}, actual interface{}, epsilon float64, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.InEpsilon")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("epsilon", epsilon))
	defer call.FinishRequire()
	upstream.InEpsilon(call.RequireT(), expected, actual, epsilon, msgAndArgs...)
}

// InEpsilonSlice is the same as InEpsilon, except it compares each value from two slices.
func InEpsilonSlice(t TestingT, expected interface{}, actual interface{}, epsilon float64, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.InEpsilonSlice")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("epsilon", epsilon))
	defer call.FinishRequire()
	upstream.InEpsilonSlice(call.RequireT(), expected, actual, epsilon, msgAndArgs...)
}

// InEpsilonSlicef is the same as InEpsilon, except it compares each value from two slices.
func InEpsilonSlicef(t TestingT, expected interface{}, actual interface{}, epsilon float64, msg string, args ...interface{}) {
	call := report.Begin(t, "require.InEpsilonSlicef")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("epsilon", epsilon))
	defer call.FinishRequire()
	upstream.InEpsilonSlicef(call.RequireT(), expected, actual, epsilon, msg, args...)
}

// InEpsilonf asserts that expected and actual have a relative error less than epsilon
func InEpsilonf(t TestingT, expected interface{}, actual interface{}, epsilon float64, msg string, args ...interface{}) {
	call := report.Begin(t, "require.InEpsilonf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("epsilon", epsilon))
	defer call.FinishRequire()
	upstream.InEpsilonf(call.RequireT(), expected, actual, epsilon, msg, args...)
}

// IsDecreasing asserts that the collection is decreasing
//
//	require.IsDecreasing(t, []int{2, 1, 0})
//	require.IsDecreasing(t, []float{2, 1})
//	require.IsDecreasing(t, []string{"b", "a"})
func IsDecreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.IsDecreasing")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.IsDecreasing(call.RequireT(), object, msgAndArgs...)
}

// IsDecreasingf asserts that the collection is decreasing
//
//	require.IsDecreasingf(t, []int{2, 1, 0}, "error message %s", "formatted")
//	require.IsDecreasingf(t, []float{2, 1}, "error message %s", "formatted")
//	require.IsDecreasingf(t, []string{"b", "a"}, "error message %s", "formatted")
func IsDecreasingf(t TestingT, object interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.IsDecreasingf")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.IsDecreasingf(call.RequireT(), object, msg, args...)
}

// IsIncreasing asserts that the collection is increasing
//
//	require.IsIncreasing(t, []int{1, 2, 3})
//	require.IsIncreasing(t, []float{1, 2})
//	require.IsIncreasing(t, []string{"a", "b"})
func IsIncreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.IsIncreasing")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.IsIncreasing(call.RequireT(), object, msgAndArgs...)
}

// IsIncreasingf asserts that the collection is increasing
//
//	require.IsIncreasingf(t, []int{1, 2, 3}, "error message %s", "formatted")
//	require.IsIncreasingf(t, []float{1, 2}, "error message %s", "formatted")
//	require.IsIncreasingf(t, []string{"a", "b"}, "error message %s", "formatted")
func IsIncreasingf(t TestingT, object interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.IsIncreasingf")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.IsIncreasingf(call.RequireT(), object, msg, args...)
}

// IsNonDecreasing asserts that the collection is not decreasing
//
//	require.IsNonDecreasing(t, []int{1, 1, 2})
//	require.IsNonDecreasing(t, []float{1, 2})
//	require.IsNonDecreasing(t, []string{"a", "b"})
func IsNonDecreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.IsNonDecreasing")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.IsNonDecreasing(call.RequireT(), object, msgAndArgs...)
}

// IsNonDecreasingf asserts that the collection is not decreasing
//
//	require.IsNonDecreasingf(t, []int{1, 1, 2}, "error message %s", "formatted")
//	require.IsNonDecreasingf(t, []float{1, 2}, "error message %s", "formatted")
//	require.IsNonDecreasingf(t, []string{"a", "b"}, "error message %s", "formatted")
func IsNonDecreasingf(t TestingT, object interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.IsNonDecreasingf")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.IsNonDecreasingf(call.RequireT(), object, msg, args...)
}

// IsNonIncreasing asserts that the collection is not increasing
//
//	require.IsNonIncreasing(t, []int{2, 1, 1})
//	require.IsNonIncreasing(t, []float{2, 1})
//	require.IsNonIncreasing(t, []string{"b", "a"})
func IsNonIncreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.IsNonIncreasing")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.IsNonIncreasing(call.RequireT(), object, msgAndArgs...)
}

// IsNonIncreasingf asserts that the collection is not increasing
//
//	require.IsNonIncreasingf(t, []int{2, 1, 1}, "error message %s", "formatted")
//	require.IsNonIncreasingf(t, []float{2, 1}, "error message %s", "formatted")
//	require.IsNonIncreasingf(t, []string{"b", "a"}, "error message %s", "formatted")
func IsNonIncreasingf(t TestingT, object interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.IsNonIncreasingf")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.IsNonIncreasingf(call.RequireT(), object, msg, args...)
}

// IsNotType asserts that the specified objects are not of the same type.
//
//	require.IsNotType(t, &NotMyStruct{}, &MyStruct{})
func IsNotType(t TestingT, theType interface{}, object interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.IsNotType")
	call.Capture(report.Arg("theType", theType), report.Arg("object", object))
	defer call.FinishRequire()
	upstream.IsNotType(call.RequireT(), theType, object, msgAndArgs...)
}

// IsNotTypef asserts that the specified objects are not of the same type.
//
//	require.IsNotTypef(t, &NotMyStruct{}, &MyStruct{}, "error message %s", "formatted")
func IsNotTypef(t TestingT, theType interface{}, object interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.IsNotTypef")
	call.Capture(report.Arg("theType", theType), report.Arg("object", object))
	defer call.FinishRequire()
	upstream.IsNotTypef(call.RequireT(), theType, object, msg, args...)
}

// IsType asserts that the specified objects are of the same type.
//
//	require.IsType(t, &MyStruct{}, &MyStruct{})
func IsType(t TestingT, expectedType interface{}, object interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.IsType")
	call.Capture(report.Arg("expectedType", expectedType), report.Arg("object", object))
	defer call.FinishRequire()
	upstream.IsType(call.RequireT(), expectedType, object, msgAndArgs...)
}

// IsTypef asserts that the specified objects are of the same type.
//
//	require.IsTypef(t, &MyStruct{}, &MyStruct{}, "error message %s", "formatted")
func IsTypef(t TestingT, expectedType interface{}, object interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.IsTypef")
	call.Capture(report.Arg("expectedType", expectedType), report.Arg("object", object))
	defer call.FinishRequire()
	upstream.IsTypef(call.RequireT(), expectedType, object, msg, args...)
}

// JSONEq asserts that two JSON strings are equivalent.
//
//	require.JSONEq(t, `{"hello": "world", "foo": "bar"}`, `{"foo": "bar", "hello": "world"}`)
func JSONEq(t TestingT, expected string, actual string, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.JSONEq")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.JSONEq(call.RequireT(), expected, actual, msgAndArgs...)
}

// JSONEqf asserts that two JSON strings are equivalent.
//
//	require.JSONEqf(t, `{"hello": "world", "foo": "bar"}`, `{"foo": "bar", "hello": "world"}`, "error message %s", "formatted")
func JSONEqf(t TestingT, expected string, actual string, msg string, args ...interface{}) {
	call := report.Begin(t, "require.JSONEqf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.JSONEqf(call.RequireT(), expected, actual, msg, args...)
}

// Len asserts that the specified object has specific length.
// Len also fails if the object has a type that len() not accept.
//
//	require.Len(t, mySlice, 3)
func Len(t TestingT, object interface{}, length int, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Len")
	call.Capture(report.Arg("object", object), report.Arg("length", length))
	defer call.FinishRequire()
	upstream.Len(call.RequireT(), object, length, msgAndArgs...)
}

// Lenf asserts that the specified object has specific length.
// Lenf also fails if the object has a type that len() not accept.
//
//	require.Lenf(t, mySlice, 3, "error message %s", "formatted")
func Lenf(t TestingT, object interface{}, length int, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Lenf")
	call.Capture(report.Arg("object", object), report.Arg("length", length))
	defer call.FinishRequire()
	upstream.Lenf(call.RequireT(), object, length, msg, args...)
}

// Less asserts that the first element is less than the second
//
//	require.Less(t, 1, 2)
//	require.Less(t, float64(1), float64(2))
//	require.Less(t, "a", "b")
func Less(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Less")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	defer call.FinishRequire()
	upstream.Less(call.RequireT(), e1, e2, msgAndArgs...)
}

// LessOrEqual asserts that the first element is less than or equal to the second
//
//	require.LessOrEqual(t, 1, 2)
//	require.LessOrEqual(t, 2, 2)
//	require.LessOrEqual(t, "a", "b")
//	require.LessOrEqual(t, "b", "b")
func LessOrEqual(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.LessOrEqual")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	defer call.FinishRequire()
	upstream.LessOrEqual(call.RequireT(), e1, e2, msgAndArgs...)
}

// LessOrEqualf asserts that the first element is less than or equal to the second
//
//	require.LessOrEqualf(t, 1, 2, "error message %s", "formatted")
//	require.LessOrEqualf(t, 2, 2, "error message %s", "formatted")
//	require.LessOrEqualf(t, "a", "b", "error message %s", "formatted")
//	require.LessOrEqualf(t, "b", "b", "error message %s", "formatted")
func LessOrEqualf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.LessOrEqualf")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	defer call.FinishRequire()
	upstream.LessOrEqualf(call.RequireT(), e1, e2, msg, args...)
}

// Lessf asserts that the first element is less than the second
//
//	require.Lessf(t, 1, 2, "error message %s", "formatted")
//	require.Lessf(t, float64(1), float64(2), "error message %s", "formatted")
//	require.Lessf(t, "a", "b", "error message %s", "formatted")
func Lessf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Lessf")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	defer call.FinishRequire()
	upstream.Lessf(call.RequireT(), e1, e2, msg, args...)
}

// Negative asserts that the specified element is negative
//
//	require.Negative(t, -1)
//	require.Negative(t, -1.23)
func Negative(t TestingT, e interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Negative")
	call.Capture(report.Arg("e", e))
	defer call.FinishRequire()
	upstream.Negative(call.RequireT(), e, msgAndArgs...)
}

// Negativef asserts that the specified element is negative
//
//	require.Negativef(t, -1, "error message %s", "formatted")
//	require.Negativef(t, -1.23, "error message %s", "formatted")
func Negativef(t TestingT, e interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Negativef")
	call.Capture(report.Arg("e", e))
	defer call.FinishRequire()
	upstream.Negativef(call.RequireT(), e, msg, args...)
}

// Never asserts that the given condition doesn't satisfy in waitFor time,
// periodically checking the target function each tick.
//
//	require.Never(t, func() bool { return false; }, time.Second, 10*time.Millisecond)
func Never(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Never")
	call.Capture(report.Arg("condition", condition), report.Arg("waitFor", waitFor), report.Arg("tick", tick))
	defer call.FinishRequire()
	upstream.Never(call.RequireT(), condition, waitFor, tick, msgAndArgs...)
}

// Neverf asserts that the given condition doesn't satisfy in waitFor time,
// periodically checking the target function each tick.
//
//	require.Neverf(t, func() bool { return false; }, time.Second, 10*time.Millisecond, "error message %s", "formatted")
func Neverf(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Neverf")
	call.Capture(report.Arg("condition", condition), report.Arg("waitFor", waitFor), report.Arg("tick", tick))
	defer call.FinishRequire()
	upstream.Neverf(call.RequireT(), condition, waitFor, tick, msg, args...)
}

// Nil asserts that the specified object is nil.
//
//	require.Nil(t, err)
func Nil(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Nil")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.Nil(call.RequireT(), object, msgAndArgs...)
}

// Nilf asserts that the specified object is nil.
//
//	require.Nilf(t, err, "error message %s", "formatted")
func Nilf(t TestingT, object interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Nilf")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.Nilf(call.RequireT(), object, msg, args...)
}

// NoDirExists checks whether a directory does not exist in the given path.
// It fails if the path points to an existing _directory_ only.
func NoDirExists(t TestingT, path string, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NoDirExists")
	call.Capture(report.Arg("path", path))
	defer call.FinishRequire()
	upstream.NoDirExists(call.RequireT(), path, msgAndArgs...)
}

// NoDirExistsf checks whether a directory does not exist in the given path.
// It fails if the path points to an existing _directory_ only.
func NoDirExistsf(t TestingT, path string, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NoDirExistsf")
	call.Capture(report.Arg("path", path))
	defer call.FinishRequire()
	upstream.NoDirExistsf(call.RequireT(), path, msg, args...)
}

// NoError asserts that a function returned no error (i.e. `nil`).
//
//	  actualObj, err := SomeFunction()
//	  if require.NoError(t, err) {
//		   require.Equal(t, expectedObj, actualObj)
//	  }
func NoError(t TestingT, err error, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NoError")
	call.Capture(report.Arg("err", err))
	defer call.FinishRequire()
	upstream.NoError(call.RequireT(), err, msgAndArgs...)
}

// NoErrorf asserts that a function returned no error (i.e. `nil`).
//
//	  actualObj, err := SomeFunction()
//	  if require.NoErrorf(t, err, "error message %s", "formatted") {
//		   require.Equal(t, expectedObj, actualObj)
//	  }
func NoErrorf(t TestingT, err error, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NoErrorf")
	call.Capture(report.Arg("err", err))
	defer call.FinishRequire()
	upstream.NoErrorf(call.RequireT(), err, msg, args...)
}

// NoFileExists checks whether a file does not exist in a given path. It fails
// if the path points to an existing _file_ only.
func NoFileExists(t TestingT, path string, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NoFileExists")
	call.Capture(report.Arg("path", path))
	defer call.FinishRequire()
	upstream.NoFileExists(call.RequireT(), path, msgAndArgs...)
}

// NoFileExistsf checks whether a file does not exist in a given path. It fails
// if the path points to an existing _file_ only.
func NoFileExistsf(t TestingT, path string, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NoFileExistsf")
	call.Capture(report.Arg("path", path))
	defer call.FinishRequire()
	upstream.NoFileExistsf(call.RequireT(), path, msg, args...)
}

// NotContains asserts that the specified string, list(array, slice...) or map does NOT contain the
// specified substring or element.
//
//	require.NotContains(t, "Hello World", "Earth")
//	require.NotContains(t, ["Hello", "World"], "Earth")
//	require.NotContains(t, {"Hello": "World"}, "Earth")
func NotContains(t TestingT, s interface{}, contains interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NotContains")
	call.Capture(report.Arg("s", s), report.Arg("contains", contains))
	defer call.FinishRequire()
	upstream.NotContains(call.RequireT(), s, contains, msgAndArgs...)
}

// NotContainsf asserts that the specified string, list(array, slice...) or map does NOT contain the
// specified substring or element.
//
//	require.NotContainsf(t, "Hello World", "Earth", "error message %s", "formatted")
//	require.NotContainsf(t, ["Hello", "World"], "Earth", "error message %s", "formatted")
//	require.NotContainsf(t, {"Hello": "World"}, "Earth", "error message %s", "formatted")
func NotContainsf(t TestingT, s interface{}, contains interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NotContainsf")
	call.Capture(report.Arg("s", s), report.Arg("contains", contains))
	defer call.FinishRequire()
	upstream.NotContainsf(call.RequireT(), s, contains, msg, args...)
}

// NotElementsMatch asserts that the specified listA(array, slice...) is NOT equal to specified
// listB(array, slice...) ignoring the order of the elements. If there are duplicate elements,
// the number of appearances of each of them in both lists should not match.
// This is an inverse of ElementsMatch.
//
// require.NotElementsMatch(t, [1, 1, 2, 3], [1, 1, 2, 3]) -> false
//
// require.NotElementsMatch(t, [1, 1, 2, 3], [1, 2, 3]) -> true
//
// require.NotElementsMatch(t, [1, 2, 3], [1, 2, 4]) -> true
func NotElementsMatch(t TestingT, listA interface{}, listB interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NotElementsMatch")
	call.Capture(report.Arg("listA", listA), report.Arg("listB", listB))
	defer call.FinishRequire()
	upstream.NotElementsMatch(call.RequireT(), listA, listB, msgAndArgs...)
}

// NotElementsMatchf asserts that the specified listA(array, slice...) is NOT equal to specified
// listB(array, slice...) ignoring the order of the elements. If there are duplicate elements,
// the number of appearances of each of them in both lists should not match.
// This is an inverse of ElementsMatch.
//
// require.NotElementsMatchf(t, [1, 1, 2, 3], [1, 1, 2, 3], "error message %s", "formatted") -> false
//
// require.NotElementsMatchf(t, [1, 1, 2, 3], [1, 2, 3], "error message %s", "formatted") -> true
//
// require.NotElementsMatchf(t, [1, 2, 3], [1, 2, 4], "error message %s", "formatted") -> true
func NotElementsMatchf(t TestingT, listA interface{}, listB interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NotElementsMatchf")
	call.Capture(report.Arg("listA", listA), report.Arg("listB", listB))
	defer call.FinishRequire()
	upstream.NotElementsMatchf(call.RequireT(), listA, listB, msg, args...)
}

// NotEmpty asserts that the specified object is NOT [Empty].
//
//	if require.NotEmpty(t, obj) {
//	  require.Equal(t, "two", obj[1])
//	}
func NotEmpty(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NotEmpty")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.NotEmpty(call.RequireT(), object, msgAndArgs...)
}

// NotEmptyf asserts that the specified object is NOT [Empty].
//
//	if require.NotEmptyf(t, obj, "error message %s", "formatted") {
//	  require.Equal(t, "two", obj[1])
//	}
func NotEmptyf(t TestingT, object interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NotEmptyf")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.NotEmptyf(call.RequireT(), object, msg, args...)
}

// NotEqual asserts that the specified values are NOT equal.
//
//	require.NotEqual(t, obj1, obj2)
//
// Pointer variable equality is determined based on the equality of the
// referenced values (as opposed to the memory addresses).
func NotEqual(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NotEqual")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.NotEqual(call.RequireT(), expected, actual, msgAndArgs...)
}

// NotEqualValues asserts that two objects are not equal even when converted to the same type
//
//	require.NotEqualValues(t, obj1, obj2)
func NotEqualValues(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NotEqualValues")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.NotEqualValues(call.RequireT(), expected, actual, msgAndArgs...)
}

// NotEqualValuesf asserts that two objects are not equal even when converted to the same type
//
//	require.NotEqualValuesf(t, obj1, obj2, "error message %s", "formatted")
func NotEqualValuesf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NotEqualValuesf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.NotEqualValuesf(call.RequireT(), expected, actual, msg, args...)
}

// NotEqualf asserts that the specified values are NOT equal.
//
//	require.NotEqualf(t, obj1, obj2, "error message %s", "formatted")
//
// Pointer variable equality is determined based on the equality of the
// referenced values (as opposed to the memory addresses).
func NotEqualf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NotEqualf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.NotEqualf(call.RequireT(), expected, actual, msg, args...)
}

// NotErrorAs asserts that none of the errors in err's chain matches target,
// but if so, sets target to that error value.
func NotErrorAs(t TestingT, err error, target interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NotErrorAs")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	defer call.FinishRequire()
	upstream.NotErrorAs(call.RequireT(), err, target, msgAndArgs...)
}

// NotErrorAsf asserts that none of the errors in err's chain matches target,
// but if so, sets target to that error value.
func NotErrorAsf(t TestingT, err error, target interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NotErrorAsf")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	defer call.FinishRequire()
	upstream.NotErrorAsf(call.RequireT(), err, target, msg, args...)
}

// NotErrorIs asserts that none of the errors in err's chain matches target.
// This is a wrapper for errors.Is.
func NotErrorIs(t TestingT, err error, target error, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NotErrorIs")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	defer call.FinishRequire()
	upstream.NotErrorIs(call.RequireT(), err, target, msgAndArgs...)
}

// NotErrorIsf asserts that none of the errors in err's chain matches target.
// This is a wrapper for errors.Is.
func NotErrorIsf(t TestingT, err error, target error, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NotErrorIsf")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	defer call.FinishRequire()
	upstream.NotErrorIsf(call.RequireT(), err, target, msg, args...)
}

// NotImplements asserts that an object does not implement the specified interface.
//
//	require.NotImplements(t, (*MyInterface)(nil), new(MyObject))
func NotImplements(t TestingT, interfaceObject interface{}, object interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NotImplements")
	call.Capture(report.Arg("interfaceObject", interfaceObject), report.Arg("object", object))
	defer call.FinishRequire()
	upstream.NotImplements(call.RequireT(), interfaceObject, object, msgAndArgs...)
}

// NotImplementsf asserts that an object does not implement the specified interface.
//
//	require.NotImplementsf(t, (*MyInterface)(nil), new(MyObject), "error message %s", "formatted")
func NotImplementsf(t TestingT, interfaceObject interface{}, object interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NotImplementsf")
	call.Capture(report.Arg("interfaceObject", interfaceObject), report.Arg("object", object))
	defer call.FinishRequire()
	upstream.NotImplementsf(call.RequireT(), interfaceObject, object, msg, args...)
}

// NotNil asserts that the specified object is not nil.
//
//	require.NotNil(t, err)
func NotNil(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NotNil")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.NotNil(call.RequireT(), object, msgAndArgs...)
}

// NotNilf asserts that the specified object is not nil.
//
//	require.NotNilf(t, err, "error message %s", "formatted")
func NotNilf(t TestingT, object interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NotNilf")
	call.Capture(report.Arg("object", object))
	defer call.FinishRequire()
	upstream.NotNilf(call.RequireT(), object, msg, args...)
}

// NotPanics asserts that the code inside the specified PanicTestFunc does NOT panic.
//
//	require.NotPanics(t, func(){ RemainCalm() })
func NotPanics(t TestingT, f assert.PanicTestFunc, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NotPanics")
	call.Capture(report.Arg("f", f))
	defer call.FinishRequire()
	upstream.NotPanics(call.RequireT(), f, msgAndArgs...)
}

// NotPanicsf asserts that the code inside the specified PanicTestFunc does NOT panic.
//
//	require.NotPanicsf(t, func(){ RemainCalm() }, "error message %s", "formatted")
func NotPanicsf(t TestingT, f assert.PanicTestFunc, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NotPanicsf")
	call.Capture(report.Arg("f", f))
	defer call.FinishRequire()
	upstream.NotPanicsf(call.RequireT(), f, msg, args...)
}

// NotRegexp asserts that a specified regexp does not match a string.
//
//	require.NotRegexp(t, regexp.MustCompile("starts"), "it's starting")
//	require.NotRegexp(t, "^start", "it's not starting")
func NotRegexp(t TestingT, rx interface{}, str interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NotRegexp")
	call.Capture(report.Arg("rx", rx), report.Arg("str", str))
	defer call.FinishRequire()
	upstream.NotRegexp(call.RequireT(), rx, str, msgAndArgs...)
}

// NotRegexpf asserts that a specified regexp does not match a string.
//
//	require.NotRegexpf(t, regexp.MustCompile("starts"), "it's starting", "error message %s", "formatted")
//	require.NotRegexpf(t, "^start", "it's not starting", "error message %s", "formatted")
func NotRegexpf(t TestingT, rx interface{}, str interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NotRegexpf")
	call.Capture(report.Arg("rx", rx), report.Arg("str", str))
	defer call.FinishRequire()
	upstream.NotRegexpf(call.RequireT(), rx, str, msg, args...)
}

// NotSame asserts that two pointers do not reference the same object.
//
//	require.NotSame(t, ptr1, ptr2)
//
// Both arguments must be pointer variables. Pointer variable sameness is
// determined based on the equality of both type and value.
func NotSame(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NotSame")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.NotSame(call.RequireT(), expected, actual, msgAndArgs...)
}

// NotSamef asserts that two pointers do not reference the same object.
//
//	require.NotSamef(t, ptr1, ptr2, "error message %s", "formatted")
//
// Both arguments must be pointer variables. Pointer variable sameness is
// determined based on the equality of both type and value.
func NotSamef(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NotSamef")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.NotSamef(call.RequireT(), expected, actual, msg, args...)
}

// NotSubset asserts that the list (array, slice, or map) does NOT contain all
// elements given in the subset (array, slice, or map).
// Map elements are key-value pairs unless compared with an array or slice where
// only the map key is evaluated.
//
//	require.NotSubset(t, [1, 3, 4], [1, 2])
//	require.NotSubset(t, {"x": 1, "y": 2}, {"z": 3})
//	require.NotSubset(t, [1, 3, 4], {1: "one", 2: "two"})
//	require.NotSubset(t, {"x": 1, "y": 2}, ["z"])
func NotSubset(t TestingT, list interface{}, subset interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NotSubset")
	call.Capture(report.Arg("list", list), report.Arg("subset", subset))
	defer call.FinishRequire()
	upstream.NotSubset(call.RequireT(), list, subset, msgAndArgs...)
}

// NotSubsetf asserts that the list (array, slice, or map) does NOT contain all
// elements given in the subset (array, slice, or map).
// Map elements are key-value pairs unless compared with an array or slice where
// only the map key is evaluated.
//
//	require.NotSubsetf(t, [1, 3, 4], [1, 2], "error message %s", "formatted")
//	require.NotSubsetf(t, {"x": 1, "y": 2}, {"z": 3}, "error message %s", "formatted")
//	require.NotSubsetf(t, [1, 3, 4], {1: "one", 2: "two"}, "error message %s", "formatted")
//	require.NotSubsetf(t, {"x": 1, "y": 2}, ["z"], "error message %s", "formatted")
func NotSubsetf(t TestingT, list interface{}, subset interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NotSubsetf")
	call.Capture(report.Arg("list", list), report.Arg("subset", subset))
	defer call.FinishRequire()
	upstream.NotSubsetf(call.RequireT(), list, subset, msg, args...)
}

// NotZero asserts that i is not the zero value for its type.
func NotZero(t TestingT, i interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.NotZero")
	call.Capture(report.Arg("i", i))
	defer call.FinishRequire()
	upstream.NotZero(call.RequireT(), i, msgAndArgs...)
}

// NotZerof asserts that i is not the zero value for its type.
func NotZerof(t TestingT, i interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.NotZerof")
	call.Capture(report.Arg("i", i))
	defer call.FinishRequire()
	upstream.NotZerof(call.RequireT(), i, msg, args...)
}

// Panics asserts that the code inside the specified PanicTestFunc panics.
//
//	require.Panics(t, func(){ GoCrazy() })
func Panics(t TestingT, f assert.PanicTestFunc, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Panics")
	call.Capture(report.Arg("f", f))
	defer call.FinishRequire()
	upstream.Panics(call.RequireT(), f, msgAndArgs...)
}

// PanicsWithError asserts that the code inside the specified PanicTestFunc
// panics, and that the recovered panic value is an error that satisfies the
// EqualError comparison.
//
//	require.PanicsWithError(t, "crazy error", func(){ GoCrazy() })
func PanicsWithError(t TestingT, errString string, f assert.PanicTestFunc, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.PanicsWithError")
	call.Capture(report.Arg("errString", errString), report.Arg("f", f))
	defer call.FinishRequire()
	upstream.PanicsWithError(call.RequireT(), errString, f, msgAndArgs...)
}

// PanicsWithErrorf asserts that the code inside the specified PanicTestFunc
// panics, and that the recovered panic value is an error that satisfies the
// EqualError comparison.
//
//	require.PanicsWithErrorf(t, "crazy error", func(){ GoCrazy() }, "error message %s", "formatted")
func PanicsWithErrorf(t TestingT, errString string, f assert.PanicTestFunc, msg string, args ...interface{}) {
	call := report.Begin(t, "require.PanicsWithErrorf")
	call.Capture(report.Arg("errString", errString), report.Arg("f", f))
	defer call.FinishRequire()
	upstream.PanicsWithErrorf(call.RequireT(), errString, f, msg, args...)
}

// PanicsWithValue asserts that the code inside the specified PanicTestFunc panics, and that
// the recovered panic value equals the expected panic value.
//
//	require.PanicsWithValue(t, "crazy error", func(){ GoCrazy() })
func PanicsWithValue(t TestingT, expected interface{}, f assert.PanicTestFunc, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.PanicsWithValue")
	call.Capture(report.Arg("expected", expected), report.Arg("f", f))
	defer call.FinishRequire()
	upstream.PanicsWithValue(call.RequireT(), expected, f, msgAndArgs...)
}

// PanicsWithValuef asserts that the code inside the specified PanicTestFunc panics, and that
// the recovered panic value equals the expected panic value.
//
//	require.PanicsWithValuef(t, "crazy error", func(){ GoCrazy() }, "error message %s", "formatted")
func PanicsWithValuef(t TestingT, expected interface{}, f assert.PanicTestFunc, msg string, args ...interface{}) {
	call := report.Begin(t, "require.PanicsWithValuef")
	call.Capture(report.Arg("expected", expected), report.Arg("f", f))
	defer call.FinishRequire()
	upstream.PanicsWithValuef(call.RequireT(), expected, f, msg, args...)
}

// Panicsf asserts that the code inside the specified PanicTestFunc panics.
//
//	require.Panicsf(t, func(){ GoCrazy() }, "error message %s", "formatted")
func Panicsf(t TestingT, f assert.PanicTestFunc, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Panicsf")
	call.Capture(report.Arg("f", f))
	defer call.FinishRequire()
	upstream.Panicsf(call.RequireT(), f, msg, args...)
}

// Positive asserts that the specified element is positive
//
//	require.Positive(t, 1)
//	require.Positive(t, 1.23)
func Positive(t TestingT, e interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Positive")
	call.Capture(report.Arg("e", e))
	defer call.FinishRequire()
	upstream.Positive(call.RequireT(), e, msgAndArgs...)
}

// Positivef asserts that the specified element is positive
//
//	require.Positivef(t, 1, "error message %s", "formatted")
//	require.Positivef(t, 1.23, "error message %s", "formatted")
func Positivef(t TestingT, e interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Positivef")
	call.Capture(report.Arg("e", e))
	defer call.FinishRequire()
	upstream.Positivef(call.RequireT(), e, msg, args...)
}

// Regexp asserts that a specified regexp matches a string.
//
//	require.Regexp(t, regexp.MustCompile("start"), "it's starting")
//	require.Regexp(t, "start...$", "it's not starting")
func Regexp(t TestingT, rx interface{}, str interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Regexp")
	call.Capture(report.Arg("rx", rx), report.Arg("str", str))
	defer call.FinishRequire()
	upstream.Regexp(call.RequireT(), rx, str, msgAndArgs...)
}

// Regexpf asserts that a specified regexp matches a string.
//
//	require.Regexpf(t, regexp.MustCompile("start"), "it's starting", "error message %s", "formatted")
//	require.Regexpf(t, "start...$", "it's not starting", "error message %s", "formatted")
func Regexpf(t TestingT, rx interface{}, str interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Regexpf")
	call.Capture(report.Arg("rx", rx), report.Arg("str", str))
	defer call.FinishRequire()
	upstream.Regexpf(call.RequireT(), rx, str, msg, args...)
}

// Same asserts that two pointers reference the same object.
//
//	require.Same(t, ptr1, ptr2)
//
// Both arguments must be pointer variables. Pointer variable sameness is
// determined based on the equality of both type and value.
func Same(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Same")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.Same(call.RequireT(), expected, actual, msgAndArgs...)
}

// Samef asserts that two pointers reference the same object.
//
//	require.Samef(t, ptr1, ptr2, "error message %s", "formatted")
//
// Both arguments must be pointer variables. Pointer variable sameness is
// determined based on the equality of both type and value.
func Samef(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Samef")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.Samef(call.RequireT(), expected, actual, msg, args...)
}

// Subset asserts that the list (array, slice, or map) contains all elements
// given in the subset (array, slice, or map).
// Map elements are key-value pairs unless compared with an array or slice where
// only the map key is evaluated.
//
//	require.Subset(t, [1, 2, 3], [1, 2])
//	require.Subset(t, {"x": 1, "y": 2}, {"x": 1})
//	require.Subset(t, [1, 2, 3], {1: "one", 2: "two"})
//	require.Subset(t, {"x": 1, "y": 2}, ["x"])
func Subset(t TestingT, list interface{}, subset interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Subset")
	call.Capture(report.Arg("list", list), report.Arg("subset", subset))
	defer call.FinishRequire()
	upstream.Subset(call.RequireT(), list, subset, msgAndArgs...)
}

// Subsetf asserts that the list (array, slice, or map) contains all elements
// given in the subset (array, slice, or map).
// Map elements are key-value pairs unless compared with an array or slice where
// only the map key is evaluated.
//
//	require.Subsetf(t, [1, 2, 3], [1, 2], "error message %s", "formatted")
//	require.Subsetf(t, {"x": 1, "y": 2}, {"x": 1}, "error message %s", "formatted")
//	require.Subsetf(t, [1, 2, 3], {1: "one", 2: "two"}, "error message %s", "formatted")
//	require.Subsetf(t, {"x": 1, "y": 2}, ["x"], "error message %s", "formatted")
func Subsetf(t TestingT, list interface{}, subset interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Subsetf")
	call.Capture(report.Arg("list", list), report.Arg("subset", subset))
	defer call.FinishRequire()
	upstream.Subsetf(call.RequireT(), list, subset, msg, args...)
}

// True asserts that the specified value is true.
//
//	require.True(t, myBool)
func True(t TestingT, value bool, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.True")
	call.Capture(report.Arg("value", value))
	defer call.FinishRequire()
	upstream.True(call.RequireT(), value, msgAndArgs...)
}

// Truef asserts that the specified value is true.
//
//	require.Truef(t, myBool, "error message %s", "formatted")
func Truef(t TestingT, value bool, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Truef")
	call.Capture(report.Arg("value", value))
	defer call.FinishRequire()
	upstream.Truef(call.RequireT(), value, msg, args...)
}

// WithinDuration asserts that the two times are within duration delta of each other.
//
//	require.WithinDuration(t, time.Now(), time.Now(), 10*time.Second)
func WithinDuration(t TestingT, expected time.Time, actual time.Time, delta time.Duration, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.WithinDuration")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	defer call.FinishRequire()
	upstream.WithinDuration(call.RequireT(), expected, actual, delta, msgAndArgs...)
}

// WithinDurationf asserts that the two times are within duration delta of each other.
//
//	require.WithinDurationf(t, time.Now(), time.Now(), 10*time.Second, "error message %s", "formatted")
func WithinDurationf(t TestingT, expected time.Time, actual time.Time, delta time.Duration, msg string, args ...interface{}) {
	call := report.Begin(t, "require.WithinDurationf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	defer call.FinishRequire()
	upstream.WithinDurationf(call.RequireT(), expected, actual, delta, msg, args...)
}

// WithinRange asserts that a time is within a time range (inclusive).
//
//	require.WithinRange(t, time.Now(), time.Now().Add(-time.Second), time.Now().Add(time.Second))
func WithinRange(t TestingT, actual time.Time, start time.Time, end time.Time, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.WithinRange")
	call.Capture(report.Arg("actual", actual), report.Arg("start", start), report.Arg("end", end))
	defer call.FinishRequire()
	upstream.WithinRange(call.RequireT(), actual, start, end, msgAndArgs...)
}

// WithinRangef asserts that a time is within a time range (inclusive).
//
//	require.WithinRangef(t, time.Now(), time.Now().Add(-time.Second), time.Now().Add(time.Second), "error message %s", "formatted")
func WithinRangef(t TestingT, actual time.Time, start time.Time, end time.Time, msg string, args ...interface{}) {
	call := report.Begin(t, "require.WithinRangef")
	call.Capture(report.Arg("actual", actual), report.Arg("start", start), report.Arg("end", end))
	defer call.FinishRequire()
	upstream.WithinRangef(call.RequireT(), actual, start, end, msg, args...)
}

// YAMLEq asserts that two YAML strings are equivalent.
func YAMLEq(t TestingT, expected string, actual string, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.YAMLEq")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.YAMLEq(call.RequireT(), expected, actual, msgAndArgs...)
}

// YAMLEqf asserts that two YAML strings are equivalent.
func YAMLEqf(t TestingT, expected string, actual string, msg string, args ...interface{}) {
	call := report.Begin(t, "require.YAMLEqf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	defer call.FinishRequire()
	upstream.YAMLEqf(call.RequireT(), expected, actual, msg, args...)
}

// Zero asserts that i is the zero value for its type.
func Zero(t TestingT, i interface{}, msgAndArgs ...interface{}) {
	call := report.Begin(t, "require.Zero")
	call.Capture(report.Arg("i", i))
	defer call.FinishRequire()
	upstream.Zero(call.RequireT(), i, msgAndArgs...)
}

// Zerof asserts that i is the zero value for its type.
func Zerof(t TestingT, i interface{}, msg string, args ...interface{}) {
	call := report.Begin(t, "require.Zerof")
	call.Capture(report.Arg("i", i))
	defer call.FinishRequire()
	upstream.Zerof(call.RequireT(), i, msg, args...)
}
