// Code generated by testify/internal/testifygen; DO NOT EDIT.

package assert

import (
	http "net/http"
	url "net/url"
	time "time"
)

// Condition proxies the package-level Condition assertion.
func (a *Assertions) Condition(comp Comparison, msgAndArgs ...interface{}) bool {
	return Condition(a.t, comp, msgAndArgs...)
}

// Conditionf proxies the package-level Conditionf assertion.
func (a *Assertions) Conditionf(comp Comparison, msg string, args ...interface{}) bool {
	return Conditionf(a.t, comp, msg, args...)
}

// Contains proxies the package-level Contains assertion.
func (a *Assertions) Contains(s interface{}, contains interface{}, msgAndArgs ...interface{}) bool {
	return Contains(a.t, s, contains, msgAndArgs...)
}

// Containsf proxies the package-level Containsf assertion.
func (a *Assertions) Containsf(s interface{}, contains interface{}, msg string, args ...interface{}) bool {
	return Containsf(a.t, s, contains, msg, args...)
}

// DirExists proxies the package-level DirExists assertion.
func (a *Assertions) DirExists(path string, msgAndArgs ...interface{}) bool {
	return DirExists(a.t, path, msgAndArgs...)
}

// DirExistsf proxies the package-level DirExistsf assertion.
func (a *Assertions) DirExistsf(path string, msg string, args ...interface{}) bool {
	return DirExistsf(a.t, path, msg, args...)
}

// ElementsMatch proxies the package-level ElementsMatch assertion.
func (a *Assertions) ElementsMatch(listA interface{}, listB interface{}, msgAndArgs ...interface{}) bool {
	return ElementsMatch(a.t, listA, listB, msgAndArgs...)
}

// ElementsMatchf proxies the package-level ElementsMatchf assertion.
func (a *Assertions) ElementsMatchf(listA interface{}, listB interface{}, msg string, args ...interface{}) bool {
	return ElementsMatchf(a.t, listA, listB, msg, args...)
}

// Empty proxies the package-level Empty assertion.
func (a *Assertions) Empty(object interface{}, msgAndArgs ...interface{}) bool {
	return Empty(a.t, object, msgAndArgs...)
}

// Emptyf proxies the package-level Emptyf assertion.
func (a *Assertions) Emptyf(object interface{}, msg string, args ...interface{}) bool {
	return Emptyf(a.t, object, msg, args...)
}

// Equal proxies the package-level Equal assertion.
func (a *Assertions) Equal(expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	return Equal(a.t, expected, actual, msgAndArgs...)
}

// EqualError proxies the package-level EqualError assertion.
func (a *Assertions) EqualError(theError error, errString string, msgAndArgs ...interface{}) bool {
	return EqualError(a.t, theError, errString, msgAndArgs...)
}

// EqualErrorf proxies the package-level EqualErrorf assertion.
func (a *Assertions) EqualErrorf(theError error, errString string, msg string, args ...interface{}) bool {
	return EqualErrorf(a.t, theError, errString, msg, args...)
}

// EqualExportedValues proxies the package-level EqualExportedValues assertion.
func (a *Assertions) EqualExportedValues(expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	return EqualExportedValues(a.t, expected, actual, msgAndArgs...)
}

// EqualExportedValuesf proxies the package-level EqualExportedValuesf assertion.
func (a *Assertions) EqualExportedValuesf(expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	return EqualExportedValuesf(a.t, expected, actual, msg, args...)
}

// EqualValues proxies the package-level EqualValues assertion.
func (a *Assertions) EqualValues(expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	return EqualValues(a.t, expected, actual, msgAndArgs...)
}

// EqualValuesf proxies the package-level EqualValuesf assertion.
func (a *Assertions) EqualValuesf(expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	return EqualValuesf(a.t, expected, actual, msg, args...)
}

// Equalf proxies the package-level Equalf assertion.
func (a *Assertions) Equalf(expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	return Equalf(a.t, expected, actual, msg, args...)
}

// Error proxies the package-level Error assertion.
func (a *Assertions) Error(err error, msgAndArgs ...interface{}) bool {
	return Error(a.t, err, msgAndArgs...)
}

// ErrorAs proxies the package-level ErrorAs assertion.
func (a *Assertions) ErrorAs(err error, target interface{}, msgAndArgs ...interface{}) bool {
	return ErrorAs(a.t, err, target, msgAndArgs...)
}

// ErrorAsf proxies the package-level ErrorAsf assertion.
func (a *Assertions) ErrorAsf(err error, target interface{}, msg string, args ...interface{}) bool {
	return ErrorAsf(a.t, err, target, msg, args...)
}

// ErrorContains proxies the package-level ErrorContains assertion.
func (a *Assertions) ErrorContains(theError error, contains string, msgAndArgs ...interface{}) bool {
	return ErrorContains(a.t, theError, contains, msgAndArgs...)
}

// ErrorContainsf proxies the package-level ErrorContainsf assertion.
func (a *Assertions) ErrorContainsf(theError error, contains string, msg string, args ...interface{}) bool {
	return ErrorContainsf(a.t, theError, contains, msg, args...)
}

// ErrorIs proxies the package-level ErrorIs assertion.
func (a *Assertions) ErrorIs(err error, target error, msgAndArgs ...interface{}) bool {
	return ErrorIs(a.t, err, target, msgAndArgs...)
}

// ErrorIsf proxies the package-level ErrorIsf assertion.
func (a *Assertions) ErrorIsf(err error, target error, msg string, args ...interface{}) bool {
	return ErrorIsf(a.t, err, target, msg, args...)
}

// Errorf proxies the package-level Errorf assertion.
func (a *Assertions) Errorf(err error, msg string, args ...interface{}) bool {
	return Errorf(a.t, err, msg, args...)
}

// Eventually proxies the package-level Eventually assertion.
func (a *Assertions) Eventually(condition func() bool, waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) bool {
	return Eventually(a.t, condition, waitFor, tick, msgAndArgs...)
}

// EventuallyWithT proxies the package-level EventuallyWithT assertion.
func (a *Assertions) EventuallyWithT(condition func(collect *CollectT), waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) bool {
	return EventuallyWithT(a.t, condition, waitFor, tick, msgAndArgs...)
}

// EventuallyWithTf proxies the package-level EventuallyWithTf assertion.
func (a *Assertions) EventuallyWithTf(condition func(collect *CollectT), waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) bool {
	return EventuallyWithTf(a.t, condition, waitFor, tick, msg, args...)
}

// Eventuallyf proxies the package-level Eventuallyf assertion.
func (a *Assertions) Eventuallyf(condition func() bool, waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) bool {
	return Eventuallyf(a.t, condition, waitFor, tick, msg, args...)
}

// Exactly proxies the package-level Exactly assertion.
func (a *Assertions) Exactly(expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	return Exactly(a.t, expected, actual, msgAndArgs...)
}

// Exactlyf proxies the package-level Exactlyf assertion.
func (a *Assertions) Exactlyf(expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	return Exactlyf(a.t, expected, actual, msg, args...)
}

// Fail proxies the package-level Fail assertion.
func (a *Assertions) Fail(failureMessage string, msgAndArgs ...interface{}) bool {
	return Fail(a.t, failureMessage, msgAndArgs...)
}

// FailNow proxies the package-level FailNow assertion.
func (a *Assertions) FailNow(failureMessage string, msgAndArgs ...interface{}) bool {
	return FailNow(a.t, failureMessage, msgAndArgs...)
}

// FailNowf proxies the package-level FailNowf assertion.
func (a *Assertions) FailNowf(failureMessage string, msg string, args ...interface{}) bool {
	return FailNowf(a.t, failureMessage, msg, args...)
}

// Failf proxies the package-level Failf assertion.
func (a *Assertions) Failf(failureMessage string, msg string, args ...interface{}) bool {
	return Failf(a.t, failureMessage, msg, args...)
}

// False proxies the package-level False assertion.
func (a *Assertions) False(value bool, msgAndArgs ...interface{}) bool {
	return False(a.t, value, msgAndArgs...)
}

// Falsef proxies the package-level Falsef assertion.
func (a *Assertions) Falsef(value bool, msg string, args ...interface{}) bool {
	return Falsef(a.t, value, msg, args...)
}

// FileExists proxies the package-level FileExists assertion.
func (a *Assertions) FileExists(path string, msgAndArgs ...interface{}) bool {
	return FileExists(a.t, path, msgAndArgs...)
}

// FileExistsf proxies the package-level FileExistsf assertion.
func (a *Assertions) FileExistsf(path string, msg string, args ...interface{}) bool {
	return FileExistsf(a.t, path, msg, args...)
}

// Greater proxies the package-level Greater assertion.
func (a *Assertions) Greater(e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) bool {
	return Greater(a.t, e1, e2, msgAndArgs...)
}

// GreaterOrEqual proxies the package-level GreaterOrEqual assertion.
func (a *Assertions) GreaterOrEqual(e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) bool {
	return GreaterOrEqual(a.t, e1, e2, msgAndArgs...)
}

// GreaterOrEqualf proxies the package-level GreaterOrEqualf assertion.
func (a *Assertions) GreaterOrEqualf(e1 interface{}, e2 interface{}, msg string, args ...interface{}) bool {
	return GreaterOrEqualf(a.t, e1, e2, msg, args...)
}

// Greaterf proxies the package-level Greaterf assertion.
func (a *Assertions) Greaterf(e1 interface{}, e2 interface{}, msg string, args ...interface{}) bool {
	return Greaterf(a.t, e1, e2, msg, args...)
}

// HTTPBodyContains proxies the package-level HTTPBodyContains assertion.
func (a *Assertions) HTTPBodyContains(handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msgAndArgs ...interface{}) bool {
	return HTTPBodyContains(a.t, handler, method, url, values, str, msgAndArgs...)
}

// HTTPBodyContainsf proxies the package-level HTTPBodyContainsf assertion.
func (a *Assertions) HTTPBodyContainsf(handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msg string, args ...interface{}) bool {
	return HTTPBodyContainsf(a.t, handler, method, url, values, str, msg, args...)
}

// HTTPBodyNotContains proxies the package-level HTTPBodyNotContains assertion.
func (a *Assertions) HTTPBodyNotContains(handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msgAndArgs ...interface{}) bool {
	return HTTPBodyNotContains(a.t, handler, method, url, values, str, msgAndArgs...)
}

// HTTPBodyNotContainsf proxies the package-level HTTPBodyNotContainsf assertion.
func (a *Assertions) HTTPBodyNotContainsf(handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msg string, args ...interface{}) bool {
	return HTTPBodyNotContainsf(a.t, handler, method, url, values, str, msg, args...)
}

// HTTPError proxies the package-level HTTPError assertion.
func (a *Assertions) HTTPError(handler http.HandlerFunc, method string, url string, values url.Values, msgAndArgs ...interface{}) bool {
	return HTTPError(a.t, handler, method, url, values, msgAndArgs...)
}

// HTTPErrorf proxies the package-level HTTPErrorf assertion.
func (a *Assertions) HTTPErrorf(handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) bool {
	return HTTPErrorf(a.t, handler, method, url, values, msg, args...)
}

// HTTPRedirect proxies the package-level HTTPRedirect assertion.
func (a *Assertions) HTTPRedirect(handler http.HandlerFunc, method string, url string, values url.Values, msgAndArgs ...interface{}) bool {
	return HTTPRedirect(a.t, handler, method, url, values, msgAndArgs...)
}

// HTTPRedirectf proxies the package-level HTTPRedirectf assertion.
func (a *Assertions) HTTPRedirectf(handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) bool {
	return HTTPRedirectf(a.t, handler, method, url, values, msg, args...)
}

// HTTPStatusCode proxies the package-level HTTPStatusCode assertion.
func (a *Assertions) HTTPStatusCode(handler http.HandlerFunc, method string, url string, values url.Values, statuscode int, msgAndArgs ...interface{}) bool {
	return HTTPStatusCode(a.t, handler, method, url, values, statuscode, msgAndArgs...)
}

// HTTPStatusCodef proxies the package-level HTTPStatusCodef assertion.
func (a *Assertions) HTTPStatusCodef(handler http.HandlerFunc, method string, url string, values url.Values, statuscode int, msg string, args ...interface{}) bool {
	return HTTPStatusCodef(a.t, handler, method, url, values, statuscode, msg, args...)
}

// HTTPSuccess proxies the package-level HTTPSuccess assertion.
func (a *Assertions) HTTPSuccess(handler http.HandlerFunc, method string, url string, values url.Values, msgAndArgs ...interface{}) bool {
	return HTTPSuccess(a.t, handler, method, url, values, msgAndArgs...)
}

// HTTPSuccessf proxies the package-level HTTPSuccessf assertion.
func (a *Assertions) HTTPSuccessf(handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) bool {
	return HTTPSuccessf(a.t, handler, method, url, values, msg, args...)
}

// Implements proxies the package-level Implements assertion.
func (a *Assertions) Implements(interfaceObject interface{}, object interface{}, msgAndArgs ...interface{}) bool {
	return Implements(a.t, interfaceObject, object, msgAndArgs...)
}

// Implementsf proxies the package-level Implementsf assertion.
func (a *Assertions) Implementsf(interfaceObject interface{}, object interface{}, msg string, args ...interface{}) bool {
	return Implementsf(a.t, interfaceObject, object, msg, args...)
}

// InDelta proxies the package-level InDelta assertion.
func (a *Assertions) InDelta(expected interface{}, actual interface{}, delta float64, msgAndArgs ...interface{}) bool {
	return InDelta(a.t, expected, actual, delta, msgAndArgs...)
}

// InDeltaMapValues proxies the package-level InDeltaMapValues assertion.
func (a *Assertions) InDeltaMapValues(expected interface{}, actual interface{}, delta float64, msgAndArgs ...interface{}) bool {
	return InDeltaMapValues(a.t, expected, actual, delta, msgAndArgs...)
}

// InDeltaMapValuesf proxies the package-level InDeltaMapValuesf assertion.
func (a *Assertions) InDeltaMapValuesf(expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) bool {
	return InDeltaMapValuesf(a.t, expected, actual, delta, msg, args...)
}

// InDeltaSlice proxies the package-level InDeltaSlice assertion.
func (a *Assertions) InDeltaSlice(expected interface{}, actual interface{}, delta float64, msgAndArgs ...interface{}) bool {
	return InDeltaSlice(a.t, expected, actual, delta, msgAndArgs...)
}

// InDeltaSlicef proxies the package-level InDeltaSlicef assertion.
func (a *Assertions) InDeltaSlicef(expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) bool {
	return InDeltaSlicef(a.t, expected, actual, delta, msg, args...)
}

// InDeltaf proxies the package-level InDeltaf assertion.
func (a *Assertions) InDeltaf(expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) bool {
	return InDeltaf(a.t, expected, actual, delta, msg, args...)
}

// InEpsilon proxies the package-level InEpsilon assertion.
func (a *Assertions) InEpsilon(expected interface{}, actual interface{}, epsilon float64, msgAndArgs ...interface{}) bool {
	return InEpsilon(a.t, expected, actual, epsilon, msgAndArgs...)
}

// InEpsilonSlice proxies the package-level InEpsilonSlice assertion.
func (a *Assertions) InEpsilonSlice(expected interface{}, actual interface{}, epsilon float64, msgAndArgs ...interface{}) bool {
	return InEpsilonSlice(a.t, expected, actual, epsilon, msgAndArgs...)
}

// InEpsilonSlicef proxies the package-level InEpsilonSlicef assertion.
func (a *Assertions) InEpsilonSlicef(expected interface{}, actual interface{}, epsilon float64, msg string, args ...interface{}) bool {
	return InEpsilonSlicef(a.t, expected, actual, epsilon, msg, args...)
}

// InEpsilonf proxies the package-level InEpsilonf assertion.
func (a *Assertions) InEpsilonf(expected interface{}, actual interface{}, epsilon float64, msg string, args ...interface{}) bool {
	return InEpsilonf(a.t, expected, actual, epsilon, msg, args...)
}

// IsDecreasing proxies the package-level IsDecreasing assertion.
func (a *Assertions) IsDecreasing(object interface{}, msgAndArgs ...interface{}) bool {
	return IsDecreasing(a.t, object, msgAndArgs...)
}

// IsDecreasingf proxies the package-level IsDecreasingf assertion.
func (a *Assertions) IsDecreasingf(object interface{}, msg string, args ...interface{}) bool {
	return IsDecreasingf(a.t, object, msg, args...)
}

// IsIncreasing proxies the package-level IsIncreasing assertion.
func (a *Assertions) IsIncreasing(object interface{}, msgAndArgs ...interface{}) bool {
	return IsIncreasing(a.t, object, msgAndArgs...)
}

// IsIncreasingf proxies the package-level IsIncreasingf assertion.
func (a *Assertions) IsIncreasingf(object interface{}, msg string, args ...interface{}) bool {
	return IsIncreasingf(a.t, object, msg, args...)
}

// IsNonDecreasing proxies the package-level IsNonDecreasing assertion.
func (a *Assertions) IsNonDecreasing(object interface{}, msgAndArgs ...interface{}) bool {
	return IsNonDecreasing(a.t, object, msgAndArgs...)
}

// IsNonDecreasingf proxies the package-level IsNonDecreasingf assertion.
func (a *Assertions) IsNonDecreasingf(object interface{}, msg string, args ...interface{}) bool {
	return IsNonDecreasingf(a.t, object, msg, args...)
}

// IsNonIncreasing proxies the package-level IsNonIncreasing assertion.
func (a *Assertions) IsNonIncreasing(object interface{}, msgAndArgs ...interface{}) bool {
	return IsNonIncreasing(a.t, object, msgAndArgs...)
}

// IsNonIncreasingf proxies the package-level IsNonIncreasingf assertion.
func (a *Assertions) IsNonIncreasingf(object interface{}, msg string, args ...interface{}) bool {
	return IsNonIncreasingf(a.t, object, msg, args...)
}

// IsNotType proxies the package-level IsNotType assertion.
func (a *Assertions) IsNotType(theType interface{}, object interface{}, msgAndArgs ...interface{}) bool {
	return IsNotType(a.t, theType, object, msgAndArgs...)
}

// IsNotTypef proxies the package-level IsNotTypef assertion.
func (a *Assertions) IsNotTypef(theType interface{}, object interface{}, msg string, args ...interface{}) bool {
	return IsNotTypef(a.t, theType, object, msg, args...)
}

// IsType proxies the package-level IsType assertion.
func (a *Assertions) IsType(expectedType interface{}, object interface{}, msgAndArgs ...interface{}) bool {
	return IsType(a.t, expectedType, object, msgAndArgs...)
}

// IsTypef proxies the package-level IsTypef assertion.
func (a *Assertions) IsTypef(expectedType interface{}, object interface{}, msg string, args ...interface{}) bool {
	return IsTypef(a.t, expectedType, object, msg, args...)
}

// JSONEq proxies the package-level JSONEq assertion.
func (a *Assertions) JSONEq(expected string, actual string, msgAndArgs ...interface{}) bool {
	return JSONEq(a.t, expected, actual, msgAndArgs...)
}

// JSONEqf proxies the package-level JSONEqf assertion.
func (a *Assertions) JSONEqf(expected string, actual string, msg string, args ...interface{}) bool {
	return JSONEqf(a.t, expected, actual, msg, args...)
}

// Len proxies the package-level Len assertion.
func (a *Assertions) Len(object interface{}, length int, msgAndArgs ...interface{}) bool {
	return Len(a.t, object, length, msgAndArgs...)
}

// Lenf proxies the package-level Lenf assertion.
func (a *Assertions) Lenf(object interface{}, length int, msg string, args ...interface{}) bool {
	return Lenf(a.t, object, length, msg, args...)
}

// Less proxies the package-level Less assertion.
func (a *Assertions) Less(e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) bool {
	return Less(a.t, e1, e2, msgAndArgs...)
}

// LessOrEqual proxies the package-level LessOrEqual assertion.
func (a *Assertions) LessOrEqual(e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) bool {
	return LessOrEqual(a.t, e1, e2, msgAndArgs...)
}

// LessOrEqualf proxies the package-level LessOrEqualf assertion.
func (a *Assertions) LessOrEqualf(e1 interface{}, e2 interface{}, msg string, args ...interface{}) bool {
	return LessOrEqualf(a.t, e1, e2, msg, args...)
}

// Lessf proxies the package-level Lessf assertion.
func (a *Assertions) Lessf(e1 interface{}, e2 interface{}, msg string, args ...interface{}) bool {
	return Lessf(a.t, e1, e2, msg, args...)
}

// Negative proxies the package-level Negative assertion.
func (a *Assertions) Negative(e interface{}, msgAndArgs ...interface{}) bool {
	return Negative(a.t, e, msgAndArgs...)
}

// Negativef proxies the package-level Negativef assertion.
func (a *Assertions) Negativef(e interface{}, msg string, args ...interface{}) bool {
	return Negativef(a.t, e, msg, args...)
}

// Never proxies the package-level Never assertion.
func (a *Assertions) Never(condition func() bool, waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) bool {
	return Never(a.t, condition, waitFor, tick, msgAndArgs...)
}

// Neverf proxies the package-level Neverf assertion.
func (a *Assertions) Neverf(condition func() bool, waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) bool {
	return Neverf(a.t, condition, waitFor, tick, msg, args...)
}

// Nil proxies the package-level Nil assertion.
func (a *Assertions) Nil(object interface{}, msgAndArgs ...interface{}) bool {
	return Nil(a.t, object, msgAndArgs...)
}

// Nilf proxies the package-level Nilf assertion.
func (a *Assertions) Nilf(object interface{}, msg string, args ...interface{}) bool {
	return Nilf(a.t, object, msg, args...)
}

// NoDirExists proxies the package-level NoDirExists assertion.
func (a *Assertions) NoDirExists(path string, msgAndArgs ...interface{}) bool {
	return NoDirExists(a.t, path, msgAndArgs...)
}

// NoDirExistsf proxies the package-level NoDirExistsf assertion.
func (a *Assertions) NoDirExistsf(path string, msg string, args ...interface{}) bool {
	return NoDirExistsf(a.t, path, msg, args...)
}

// NoError proxies the package-level NoError assertion.
func (a *Assertions) NoError(err error, msgAndArgs ...interface{}) bool {
	return NoError(a.t, err, msgAndArgs...)
}

// NoErrorf proxies the package-level NoErrorf assertion.
func (a *Assertions) NoErrorf(err error, msg string, args ...interface{}) bool {
	return NoErrorf(a.t, err, msg, args...)
}

// NoFileExists proxies the package-level NoFileExists assertion.
func (a *Assertions) NoFileExists(path string, msgAndArgs ...interface{}) bool {
	return NoFileExists(a.t, path, msgAndArgs...)
}

// NoFileExistsf proxies the package-level NoFileExistsf assertion.
func (a *Assertions) NoFileExistsf(path string, msg string, args ...interface{}) bool {
	return NoFileExistsf(a.t, path, msg, args...)
}

// NotContains proxies the package-level NotContains assertion.
func (a *Assertions) NotContains(s interface{}, contains interface{}, msgAndArgs ...interface{}) bool {
	return NotContains(a.t, s, contains, msgAndArgs...)
}

// NotContainsf proxies the package-level NotContainsf assertion.
func (a *Assertions) NotContainsf(s interface{}, contains interface{}, msg string, args ...interface{}) bool {
	return NotContainsf(a.t, s, contains, msg, args...)
}

// NotElementsMatch proxies the package-level NotElementsMatch assertion.
func (a *Assertions) NotElementsMatch(listA interface{}, listB interface{}, msgAndArgs ...interface{}) bool {
	return NotElementsMatch(a.t, listA, listB, msgAndArgs...)
}

// NotElementsMatchf proxies the package-level NotElementsMatchf assertion.
func (a *Assertions) NotElementsMatchf(listA interface{}, listB interface{}, msg string, args ...interface{}) bool {
	return NotElementsMatchf(a.t, listA, listB, msg, args...)
}

// NotEmpty proxies the package-level NotEmpty assertion.
func (a *Assertions) NotEmpty(object interface{}, msgAndArgs ...interface{}) bool {
	return NotEmpty(a.t, object, msgAndArgs...)
}

// NotEmptyf proxies the package-level NotEmptyf assertion.
func (a *Assertions) NotEmptyf(object interface{}, msg string, args ...interface{}) bool {
	return NotEmptyf(a.t, object, msg, args...)
}

// NotEqual proxies the package-level NotEqual assertion.
func (a *Assertions) NotEqual(expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	return NotEqual(a.t, expected, actual, msgAndArgs...)
}

// NotEqualValues proxies the package-level NotEqualValues assertion.
func (a *Assertions) NotEqualValues(expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	return NotEqualValues(a.t, expected, actual, msgAndArgs...)
}

// NotEqualValuesf proxies the package-level NotEqualValuesf assertion.
func (a *Assertions) NotEqualValuesf(expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	return NotEqualValuesf(a.t, expected, actual, msg, args...)
}

// NotEqualf proxies the package-level NotEqualf assertion.
func (a *Assertions) NotEqualf(expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	return NotEqualf(a.t, expected, actual, msg, args...)
}

// NotErrorAs proxies the package-level NotErrorAs assertion.
func (a *Assertions) NotErrorAs(err error, target interface{}, msgAndArgs ...interface{}) bool {
	return NotErrorAs(a.t, err, target, msgAndArgs...)
}

// NotErrorAsf proxies the package-level NotErrorAsf assertion.
func (a *Assertions) NotErrorAsf(err error, target interface{}, msg string, args ...interface{}) bool {
	return NotErrorAsf(a.t, err, target, msg, args...)
}

// NotErrorIs proxies the package-level NotErrorIs assertion.
func (a *Assertions) NotErrorIs(err error, target error, msgAndArgs ...interface{}) bool {
	return NotErrorIs(a.t, err, target, msgAndArgs...)
}

// NotErrorIsf proxies the package-level NotErrorIsf assertion.
func (a *Assertions) NotErrorIsf(err error, target error, msg string, args ...interface{}) bool {
	return NotErrorIsf(a.t, err, target, msg, args...)
}

// NotImplements proxies the package-level NotImplements assertion.
func (a *Assertions) NotImplements(interfaceObject interface{}, object interface{}, msgAndArgs ...interface{}) bool {
	return NotImplements(a.t, interfaceObject, object, msgAndArgs...)
}

// NotImplementsf proxies the package-level NotImplementsf assertion.
func (a *Assertions) NotImplementsf(interfaceObject interface{}, object interface{}, msg string, args ...interface{}) bool {
	return NotImplementsf(a.t, interfaceObject, object, msg, args...)
}

// NotNil proxies the package-level NotNil assertion.
func (a *Assertions) NotNil(object interface{}, msgAndArgs ...interface{}) bool {
	return NotNil(a.t, object, msgAndArgs...)
}

// NotNilf proxies the package-level NotNilf assertion.
func (a *Assertions) NotNilf(object interface{}, msg string, args ...interface{}) bool {
	return NotNilf(a.t, object, msg, args...)
}

// NotPanics proxies the package-level NotPanics assertion.
func (a *Assertions) NotPanics(f PanicTestFunc, msgAndArgs ...interface{}) bool {
	return NotPanics(a.t, f, msgAndArgs...)
}

// NotPanicsf proxies the package-level NotPanicsf assertion.
func (a *Assertions) NotPanicsf(f PanicTestFunc, msg string, args ...interface{}) bool {
	return NotPanicsf(a.t, f, msg, args...)
}

// NotRegexp proxies the package-level NotRegexp assertion.
func (a *Assertions) NotRegexp(rx interface{}, str interface{}, msgAndArgs ...interface{}) bool {
	return NotRegexp(a.t, rx, str, msgAndArgs...)
}

// NotRegexpf proxies the package-level NotRegexpf assertion.
func (a *Assertions) NotRegexpf(rx interface{}, str interface{}, msg string, args ...interface{}) bool {
	return NotRegexpf(a.t, rx, str, msg, args...)
}

// NotSame proxies the package-level NotSame assertion.
func (a *Assertions) NotSame(expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	return NotSame(a.t, expected, actual, msgAndArgs...)
}

// NotSamef proxies the package-level NotSamef assertion.
func (a *Assertions) NotSamef(expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	return NotSamef(a.t, expected, actual, msg, args...)
}

// NotSubset proxies the package-level NotSubset assertion.
func (a *Assertions) NotSubset(list interface{}, subset interface{}, msgAndArgs ...interface{}) bool {
	return NotSubset(a.t, list, subset, msgAndArgs...)
}

// NotSubsetf proxies the package-level NotSubsetf assertion.
func (a *Assertions) NotSubsetf(list interface{}, subset interface{}, msg string, args ...interface{}) bool {
	return NotSubsetf(a.t, list, subset, msg, args...)
}

// NotZero proxies the package-level NotZero assertion.
func (a *Assertions) NotZero(i interface{}, msgAndArgs ...interface{}) bool {
	return NotZero(a.t, i, msgAndArgs...)
}

// NotZerof proxies the package-level NotZerof assertion.
func (a *Assertions) NotZerof(i interface{}, msg string, args ...interface{}) bool {
	return NotZerof(a.t, i, msg, args...)
}

// Panics proxies the package-level Panics assertion.
func (a *Assertions) Panics(f PanicTestFunc, msgAndArgs ...interface{}) bool {
	return Panics(a.t, f, msgAndArgs...)
}

// PanicsWithError proxies the package-level PanicsWithError assertion.
func (a *Assertions) PanicsWithError(errString string, f PanicTestFunc, msgAndArgs ...interface{}) bool {
	return PanicsWithError(a.t, errString, f, msgAndArgs...)
}

// PanicsWithErrorf proxies the package-level PanicsWithErrorf assertion.
func (a *Assertions) PanicsWithErrorf(errString string, f PanicTestFunc, msg string, args ...interface{}) bool {
	return PanicsWithErrorf(a.t, errString, f, msg, args...)
}

// PanicsWithValue proxies the package-level PanicsWithValue assertion.
func (a *Assertions) PanicsWithValue(expected interface{}, f PanicTestFunc, msgAndArgs ...interface{}) bool {
	return PanicsWithValue(a.t, expected, f, msgAndArgs...)
}

// PanicsWithValuef proxies the package-level PanicsWithValuef assertion.
func (a *Assertions) PanicsWithValuef(expected interface{}, f PanicTestFunc, msg string, args ...interface{}) bool {
	return PanicsWithValuef(a.t, expected, f, msg, args...)
}

// Panicsf proxies the package-level Panicsf assertion.
func (a *Assertions) Panicsf(f PanicTestFunc, msg string, args ...interface{}) bool {
	return Panicsf(a.t, f, msg, args...)
}

// Positive proxies the package-level Positive assertion.
func (a *Assertions) Positive(e interface{}, msgAndArgs ...interface{}) bool {
	return Positive(a.t, e, msgAndArgs...)
}

// Positivef proxies the package-level Positivef assertion.
func (a *Assertions) Positivef(e interface{}, msg string, args ...interface{}) bool {
	return Positivef(a.t, e, msg, args...)
}

// Regexp proxies the package-level Regexp assertion.
func (a *Assertions) Regexp(rx interface{}, str interface{}, msgAndArgs ...interface{}) bool {
	return Regexp(a.t, rx, str, msgAndArgs...)
}

// Regexpf proxies the package-level Regexpf assertion.
func (a *Assertions) Regexpf(rx interface{}, str interface{}, msg string, args ...interface{}) bool {
	return Regexpf(a.t, rx, str, msg, args...)
}

// Same proxies the package-level Same assertion.
func (a *Assertions) Same(expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	return Same(a.t, expected, actual, msgAndArgs...)
}

// Samef proxies the package-level Samef assertion.
func (a *Assertions) Samef(expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	return Samef(a.t, expected, actual, msg, args...)
}

// Subset proxies the package-level Subset assertion.
func (a *Assertions) Subset(list interface{}, subset interface{}, msgAndArgs ...interface{}) bool {
	return Subset(a.t, list, subset, msgAndArgs...)
}

// Subsetf proxies the package-level Subsetf assertion.
func (a *Assertions) Subsetf(list interface{}, subset interface{}, msg string, args ...interface{}) bool {
	return Subsetf(a.t, list, subset, msg, args...)
}

// True proxies the package-level True assertion.
func (a *Assertions) True(value bool, msgAndArgs ...interface{}) bool {
	return True(a.t, value, msgAndArgs...)
}

// Truef proxies the package-level Truef assertion.
func (a *Assertions) Truef(value bool, msg string, args ...interface{}) bool {
	return Truef(a.t, value, msg, args...)
}

// WithinDuration proxies the package-level WithinDuration assertion.
func (a *Assertions) WithinDuration(expected time.Time, actual time.Time, delta time.Duration, msgAndArgs ...interface{}) bool {
	return WithinDuration(a.t, expected, actual, delta, msgAndArgs...)
}

// WithinDurationf proxies the package-level WithinDurationf assertion.
func (a *Assertions) WithinDurationf(expected time.Time, actual time.Time, delta time.Duration, msg string, args ...interface{}) bool {
	return WithinDurationf(a.t, expected, actual, delta, msg, args...)
}

// WithinRange proxies the package-level WithinRange assertion.
func (a *Assertions) WithinRange(actual time.Time, start time.Time, end time.Time, msgAndArgs ...interface{}) bool {
	return WithinRange(a.t, actual, start, end, msgAndArgs...)
}

// WithinRangef proxies the package-level WithinRangef assertion.
func (a *Assertions) WithinRangef(actual time.Time, start time.Time, end time.Time, msg string, args ...interface{}) bool {
	return WithinRangef(a.t, actual, start, end, msg, args...)
}

// YAMLEq proxies the package-level YAMLEq assertion.
func (a *Assertions) YAMLEq(expected string, actual string, msgAndArgs ...interface{}) bool {
	return YAMLEq(a.t, expected, actual, msgAndArgs...)
}

// YAMLEqf proxies the package-level YAMLEqf assertion.
func (a *Assertions) YAMLEqf(expected string, actual string, msg string, args ...interface{}) bool {
	return YAMLEqf(a.t, expected, actual, msg, args...)
}

// Zero proxies the package-level Zero assertion.
func (a *Assertions) Zero(i interface{}, msgAndArgs ...interface{}) bool {
	return Zero(a.t, i, msgAndArgs...)
}

// Zerof proxies the package-level Zerof assertion.
func (a *Assertions) Zerof(i interface{}, msg string, args ...interface{}) bool {
	return Zerof(a.t, i, msg, args...)
}
