// Code generated by testify/internal/testifygen; DO NOT EDIT.

package assert

import (
	http "net/http"
	url "net/url"
	time "time"

	report "github.com/allure-framework/allure-go/testify/internal/report"
	upstream "github.com/stretchr/testify/assert"
)

// CallerInfo returns an array of strings containing the file and line number
// of each stack frame leading from the current test to the assert call that
// failed.
func CallerInfo() []string {
	return upstream.CallerInfo()
}

// Condition uses a Comparison to assert a complex condition.
func Condition(t TestingT, comp Comparison, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Condition")
	call.Capture(report.Arg("comp", comp))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Condition(call.AssertT(), comp, msgAndArgs...)
	return passed
}

// Conditionf uses a Comparison to assert a complex condition.
func Conditionf(t TestingT, comp Comparison, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Conditionf")
	call.Capture(report.Arg("comp", comp))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Conditionf(call.AssertT(), comp, msg, args...)
	return passed
}

// Contains asserts that the specified string, list(array, slice...) or map contains the
// specified substring or element.
//
//	assert.Contains(t, "Hello World", "World")
//	assert.Contains(t, ["Hello", "World"], "World")
//	assert.Contains(t, {"Hello": "World"}, "Hello")
func Contains(t TestingT, s interface{}, contains interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Contains")
	call.Capture(report.Arg("s", s), report.Arg("contains", contains))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Contains(call.AssertT(), s, contains, msgAndArgs...)
	return passed
}

// Containsf asserts that the specified string, list(array, slice...) or map contains the
// specified substring or element.
//
//	assert.Containsf(t, "Hello World", "World", "error message %s", "formatted")
//	assert.Containsf(t, ["Hello", "World"], "World", "error message %s", "formatted")
//	assert.Containsf(t, {"Hello": "World"}, "Hello", "error message %s", "formatted")
func Containsf(t TestingT, s interface{}, contains interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Containsf")
	call.Capture(report.Arg("s", s), report.Arg("contains", contains))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Containsf(call.AssertT(), s, contains, msg, args...)
	return passed
}

// DirExists checks whether a directory exists in the given path. It also fails
// if the path is a file rather a directory or there is an error checking whether it exists.
func DirExists(t TestingT, path string, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.DirExists")
	call.Capture(report.Arg("path", path))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.DirExists(call.AssertT(), path, msgAndArgs...)
	return passed
}

// DirExistsf checks whether a directory exists in the given path. It also fails
// if the path is a file rather a directory or there is an error checking whether it exists.
func DirExistsf(t TestingT, path string, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.DirExistsf")
	call.Capture(report.Arg("path", path))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.DirExistsf(call.AssertT(), path, msg, args...)
	return passed
}

// ElementsMatch asserts that the specified listA(array, slice...) is equal to specified
// listB(array, slice...) ignoring the order of the elements. If there are duplicate elements,
// the number of appearances of each of them in both lists should match.
//
// assert.ElementsMatch(t, [1, 3, 2, 3], [1, 3, 3, 2])
func ElementsMatch(t TestingT, listA interface{}, listB interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.ElementsMatch")
	call.Capture(report.Arg("listA", listA), report.Arg("listB", listB))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.ElementsMatch(call.AssertT(), listA, listB, msgAndArgs...)
	return passed
}

// ElementsMatchf asserts that the specified listA(array, slice...) is equal to specified
// listB(array, slice...) ignoring the order of the elements. If there are duplicate elements,
// the number of appearances of each of them in both lists should match.
//
// assert.ElementsMatchf(t, [1, 3, 2, 3], [1, 3, 3, 2], "error message %s", "formatted")
func ElementsMatchf(t TestingT, listA interface{}, listB interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.ElementsMatchf")
	call.Capture(report.Arg("listA", listA), report.Arg("listB", listB))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.ElementsMatchf(call.AssertT(), listA, listB, msg, args...)
	return passed
}

// Empty asserts that the given value is "empty".
//
// [Zero values] are "empty".
//
// Arrays are "empty" if every element is the zero value of the type (stricter than "empty").
//
// Slices, maps and channels with zero length are "empty".
//
// Pointer values are "empty" if the pointer is nil or if the pointed value is "empty".
//
//	assert.Empty(t, obj)
//
// [Zero values]: https://go.dev/ref/spec#The_zero_value
func Empty(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Empty")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Empty(call.AssertT(), object, msgAndArgs...)
	return passed
}

// Emptyf asserts that the given value is "empty".
//
// [Zero values] are "empty".
//
// Arrays are "empty" if every element is the zero value of the type (stricter than "empty").
//
// Slices, maps and channels with zero length are "empty".
//
// Pointer values are "empty" if the pointer is nil or if the pointed value is "empty".
//
//	assert.Emptyf(t, obj, "error message %s", "formatted")
//
// [Zero values]: https://go.dev/ref/spec#The_zero_value
func Emptyf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Emptyf")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Emptyf(call.AssertT(), object, msg, args...)
	return passed
}

// Equal asserts that two objects are equal.
//
//	assert.Equal(t, 123, 123)
//
// Pointer variable equality is determined based on the equality of the
// referenced values (as opposed to the memory addresses). Function equality
// cannot be determined and will always fail.
func Equal(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Equal")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Equal(call.AssertT(), expected, actual, msgAndArgs...)
	return passed
}

// EqualError asserts that a function returned an error (i.e. not `nil`)
// and that it is equal to the provided error.
//
//	actualObj, err := SomeFunction()
//	assert.EqualError(t, err,  expectedErrorString)
func EqualError(t TestingT, theError error, errString string, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.EqualError")
	call.Capture(report.Arg("theError", theError), report.Arg("errString", errString))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.EqualError(call.AssertT(), theError, errString, msgAndArgs...)
	return passed
}

// EqualErrorf asserts that a function returned an error (i.e. not `nil`)
// and that it is equal to the provided error.
//
//	actualObj, err := SomeFunction()
//	assert.EqualErrorf(t, err,  expectedErrorString, "error message %s", "formatted")
func EqualErrorf(t TestingT, theError error, errString string, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.EqualErrorf")
	call.Capture(report.Arg("theError", theError), report.Arg("errString", errString))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.EqualErrorf(call.AssertT(), theError, errString, msg, args...)
	return passed
}

// EqualExportedValues asserts that the types of two objects are equal and their public
// fields are also equal. This is useful for comparing structs that have private fields
// that could potentially differ.
//
//	 type S struct {
//		Exported     	int
//		notExported   	int
//	 }
//	 assert.EqualExportedValues(t, S{1, 2}, S{1, 3}) => true
//	 assert.EqualExportedValues(t, S{1, 2}, S{2, 3}) => false
func EqualExportedValues(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.EqualExportedValues")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.EqualExportedValues(call.AssertT(), expected, actual, msgAndArgs...)
	return passed
}

// EqualExportedValuesf asserts that the types of two objects are equal and their public
// fields are also equal. This is useful for comparing structs that have private fields
// that could potentially differ.
//
//	 type S struct {
//		Exported     	int
//		notExported   	int
//	 }
//	 assert.EqualExportedValuesf(t, S{1, 2}, S{1, 3}, "error message %s", "formatted") => true
//	 assert.EqualExportedValuesf(t, S{1, 2}, S{2, 3}, "error message %s", "formatted") => false
func EqualExportedValuesf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.EqualExportedValuesf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.EqualExportedValuesf(call.AssertT(), expected, actual, msg, args...)
	return passed
}

// EqualValues asserts that two objects are equal or convertible to the larger
// type and equal.
//
//	assert.EqualValues(t, uint32(123), int32(123))
func EqualValues(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.EqualValues")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.EqualValues(call.AssertT(), expected, actual, msgAndArgs...)
	return passed
}

// EqualValuesf asserts that two objects are equal or convertible to the larger
// type and equal.
//
//	assert.EqualValuesf(t, uint32(123), int32(123), "error message %s", "formatted")
func EqualValuesf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.EqualValuesf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.EqualValuesf(call.AssertT(), expected, actual, msg, args...)
	return passed
}

// Equalf asserts that two objects are equal.
//
//	assert.Equalf(t, 123, 123, "error message %s", "formatted")
//
// Pointer variable equality is determined based on the equality of the
// referenced values (as opposed to the memory addresses). Function equality
// cannot be determined and will always fail.
func Equalf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Equalf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Equalf(call.AssertT(), expected, actual, msg, args...)
	return passed
}

// Error asserts that a function returned an error (i.e. not `nil`).
//
//	actualObj, err := SomeFunction()
//	assert.Error(t, err)
func Error(t TestingT, err error, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Error")
	call.Capture(report.Arg("err", err))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Error(call.AssertT(), err, msgAndArgs...)
	return passed
}

// ErrorAs asserts that at least one of the errors in err's chain matches target, and if so, sets target to that error value.
// This is a wrapper for errors.As.
func ErrorAs(t TestingT, err error, target interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.ErrorAs")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.ErrorAs(call.AssertT(), err, target, msgAndArgs...)
	return passed
}

// ErrorAsf asserts that at least one of the errors in err's chain matches target, and if so, sets target to that error value.
// This is a wrapper for errors.As.
func ErrorAsf(t TestingT, err error, target interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.ErrorAsf")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.ErrorAsf(call.AssertT(), err, target, msg, args...)
	return passed
}

// ErrorContains asserts that a function returned an error (i.e. not `nil`)
// and that the error contains the specified substring.
//
//	actualObj, err := SomeFunction()
//	assert.ErrorContains(t, err,  expectedErrorSubString)
func ErrorContains(t TestingT, theError error, contains string, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.ErrorContains")
	call.Capture(report.Arg("theError", theError), report.Arg("contains", contains))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.ErrorContains(call.AssertT(), theError, contains, msgAndArgs...)
	return passed
}

// ErrorContainsf asserts that a function returned an error (i.e. not `nil`)
// and that the error contains the specified substring.
//
//	actualObj, err := SomeFunction()
//	assert.ErrorContainsf(t, err,  expectedErrorSubString, "error message %s", "formatted")
func ErrorContainsf(t TestingT, theError error, contains string, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.ErrorContainsf")
	call.Capture(report.Arg("theError", theError), report.Arg("contains", contains))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.ErrorContainsf(call.AssertT(), theError, contains, msg, args...)
	return passed
}

// ErrorIs asserts that at least one of the errors in err's chain matches target.
// This is a wrapper for errors.Is.
func ErrorIs(t TestingT, err error, target error, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.ErrorIs")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.ErrorIs(call.AssertT(), err, target, msgAndArgs...)
	return passed
}

// ErrorIsf asserts that at least one of the errors in err's chain matches target.
// This is a wrapper for errors.Is.
func ErrorIsf(t TestingT, err error, target error, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.ErrorIsf")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.ErrorIsf(call.AssertT(), err, target, msg, args...)
	return passed
}

// Errorf asserts that a function returned an error (i.e. not `nil`).
//
//	actualObj, err := SomeFunction()
//	assert.Errorf(t, err, "error message %s", "formatted")
func Errorf(t TestingT, err error, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Errorf")
	call.Capture(report.Arg("err", err))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Errorf(call.AssertT(), err, msg, args...)
	return passed
}

// Eventually asserts that given condition will be met in waitFor time,
// periodically checking target function each tick.
//
//	assert.Eventually(t, func() bool { return true; }, time.Second, 10*time.Millisecond)
func Eventually(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Eventually")
	call.Capture(report.Arg("condition", condition), report.Arg("waitFor", waitFor), report.Arg("tick", tick))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Eventually(call.AssertT(), condition, waitFor, tick, msgAndArgs...)
	return passed
}

// EventuallyWithT asserts that given condition will be met in waitFor time,
// periodically checking target function each tick. In contrast to Eventually,
// it supplies a CollectT to the condition function, so that the condition
// function can use the CollectT to call other assertions.
// The condition is considered "met" if no errors are raised in a tick.
// The supplied CollectT collects all errors from one tick (if there are any).
// If the condition is not met before waitFor, the collected errors of
// the last tick are copied to t.
//
//	externalValue := false
//	go func() {
//		time.Sleep(8*time.Second)
//		externalValue = true
//	}()
//	assert.EventuallyWithT(t, func(c *assert.CollectT) {
//		// add assertions as needed; any assertion failure will fail the current tick
//		assert.True(c, externalValue, "expected 'externalValue' to be true")
//	}, 10*time.Second, 1*time.Second, "external state has not changed to 'true'; still false")
func EventuallyWithT(t TestingT, condition func(collect *CollectT), waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.EventuallyWithT")
	call.Capture(report.Arg("condition", condition), report.Arg("waitFor", waitFor), report.Arg("tick", tick))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.EventuallyWithT(call.AssertT(), condition, waitFor, tick, msgAndArgs...)
	return passed
}

// EventuallyWithTf asserts that given condition will be met in waitFor time,
// periodically checking target function each tick. In contrast to Eventually,
// it supplies a CollectT to the condition function, so that the condition
// function can use the CollectT to call other assertions.
// The condition is considered "met" if no errors are raised in a tick.
// The supplied CollectT collects all errors from one tick (if there are any).
// If the condition is not met before waitFor, the collected errors of
// the last tick are copied to t.
//
//	externalValue := false
//	go func() {
//		time.Sleep(8*time.Second)
//		externalValue = true
//	}()
//	assert.EventuallyWithTf(t, func(c *assert.CollectT, "error message %s", "formatted") {
//		// add assertions as needed; any assertion failure will fail the current tick
//		assert.True(c, externalValue, "expected 'externalValue' to be true")
//	}, 10*time.Second, 1*time.Second, "external state has not changed to 'true'; still false")
func EventuallyWithTf(t TestingT, condition func(collect *CollectT), waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.EventuallyWithTf")
	call.Capture(report.Arg("condition", condition), report.Arg("waitFor", waitFor), report.Arg("tick", tick))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.EventuallyWithTf(call.AssertT(), condition, waitFor, tick, msg, args...)
	return passed
}

// Eventuallyf asserts that given condition will be met in waitFor time,
// periodically checking target function each tick.
//
//	assert.Eventuallyf(t, func() bool { return true; }, time.Second, 10*time.Millisecond, "error message %s", "formatted")
func Eventuallyf(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Eventuallyf")
	call.Capture(report.Arg("condition", condition), report.Arg("waitFor", waitFor), report.Arg("tick", tick))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Eventuallyf(call.AssertT(), condition, waitFor, tick, msg, args...)
	return passed
}

// Exactly asserts that two objects are equal in value and type.
//
//	assert.Exactly(t, int32(123), int64(123))
func Exactly(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Exactly")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Exactly(call.AssertT(), expected, actual, msgAndArgs...)
	return passed
}

// Exactlyf asserts that two objects are equal in value and type.
//
//	assert.Exactlyf(t, int32(123), int64(123), "error message %s", "formatted")
func Exactlyf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Exactlyf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Exactlyf(call.AssertT(), expected, actual, msg, args...)
	return passed
}

// Fail reports a failure through
func Fail(t TestingT, failureMessage string, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Fail")
	call.Capture(report.Arg("failureMessage", failureMessage))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Fail(call.AssertT(), failureMessage, msgAndArgs...)
	return passed
}

// FailNow fails test
func FailNow(t TestingT, failureMessage string, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.FailNow")
	call.Capture(report.Arg("failureMessage", failureMessage))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.FailNow(call.AssertT(), failureMessage, msgAndArgs...)
	return passed
}

// FailNowf fails test
func FailNowf(t TestingT, failureMessage string, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.FailNowf")
	call.Capture(report.Arg("failureMessage", failureMessage))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.FailNowf(call.AssertT(), failureMessage, msg, args...)
	return passed
}

// Failf reports a failure through
func Failf(t TestingT, failureMessage string, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Failf")
	call.Capture(report.Arg("failureMessage", failureMessage))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Failf(call.AssertT(), failureMessage, msg, args...)
	return passed
}

// False asserts that the specified value is false.
//
//	assert.False(t, myBool)
func False(t TestingT, value bool, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.False")
	call.Capture(report.Arg("value", value))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.False(call.AssertT(), value, msgAndArgs...)
	return passed
}

// Falsef asserts that the specified value is false.
//
//	assert.Falsef(t, myBool, "error message %s", "formatted")
func Falsef(t TestingT, value bool, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Falsef")
	call.Capture(report.Arg("value", value))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Falsef(call.AssertT(), value, msg, args...)
	return passed
}

// FileExists checks whether a file exists in the given path. It also fails if
// the path points to a directory or there is an error when trying to check the file.
func FileExists(t TestingT, path string, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.FileExists")
	call.Capture(report.Arg("path", path))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.FileExists(call.AssertT(), path, msgAndArgs...)
	return passed
}

// FileExistsf checks whether a file exists in the given path. It also fails if
// the path points to a directory or there is an error when trying to check the file.
func FileExistsf(t TestingT, path string, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.FileExistsf")
	call.Capture(report.Arg("path", path))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.FileExistsf(call.AssertT(), path, msg, args...)
	return passed
}

// Greater asserts that the first element is greater than the second
//
//	assert.Greater(t, 2, 1)
//	assert.Greater(t, float64(2), float64(1))
//	assert.Greater(t, "b", "a")
func Greater(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Greater")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Greater(call.AssertT(), e1, e2, msgAndArgs...)
	return passed
}

// GreaterOrEqual asserts that the first element is greater than or equal to the second
//
//	assert.GreaterOrEqual(t, 2, 1)
//	assert.GreaterOrEqual(t, 2, 2)
//	assert.GreaterOrEqual(t, "b", "a")
//	assert.GreaterOrEqual(t, "b", "b")
func GreaterOrEqual(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.GreaterOrEqual")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.GreaterOrEqual(call.AssertT(), e1, e2, msgAndArgs...)
	return passed
}

// GreaterOrEqualf asserts that the first element is greater than or equal to the second
//
//	assert.GreaterOrEqualf(t, 2, 1, "error message %s", "formatted")
//	assert.GreaterOrEqualf(t, 2, 2, "error message %s", "formatted")
//	assert.GreaterOrEqualf(t, "b", "a", "error message %s", "formatted")
//	assert.GreaterOrEqualf(t, "b", "b", "error message %s", "formatted")
func GreaterOrEqualf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.GreaterOrEqualf")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.GreaterOrEqualf(call.AssertT(), e1, e2, msg, args...)
	return passed
}

// Greaterf asserts that the first element is greater than the second
//
//	assert.Greaterf(t, 2, 1, "error message %s", "formatted")
//	assert.Greaterf(t, float64(2), float64(1), "error message %s", "formatted")
//	assert.Greaterf(t, "b", "a", "error message %s", "formatted")
func Greaterf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Greaterf")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Greaterf(call.AssertT(), e1, e2, msg, args...)
	return passed
}

// HTTPBody is a helper that returns HTTP body of the response. It returns
// empty string if building a new request fails.
func HTTPBody(handler http.HandlerFunc, method string, url string, values url.Values) string {
	return upstream.HTTPBody(handler, method, url, values)
}

// HTTPBodyContains asserts that a specified handler returns a
// body that contains a string.
//
//	assert.HTTPBodyContains(t, myHandler, "GET", "www.google.com", nil, "I'm Feeling Lucky")
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPBodyContains(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.HTTPBodyContains")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values), report.Arg("str", str))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.HTTPBodyContains(call.AssertT(), handler, method, url, values, str, msgAndArgs...)
	return passed
}

// HTTPBodyContainsf asserts that a specified handler returns a
// body that contains a string.
//
//	assert.HTTPBodyContainsf(t, myHandler, "GET", "www.google.com", nil, "I'm Feeling Lucky", "error message %s", "formatted")
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPBodyContainsf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.HTTPBodyContainsf")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values), report.Arg("str", str))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.HTTPBodyContainsf(call.AssertT(), handler, method, url, values, str, msg, args...)
	return passed
}

// HTTPBodyNotContains asserts that a specified handler returns a
// body that does not contain a string.
//
//	assert.HTTPBodyNotContains(t, myHandler, "GET", "www.google.com", nil, "I'm Feeling Lucky")
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPBodyNotContains(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.HTTPBodyNotContains")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values), report.Arg("str", str))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.HTTPBodyNotContains(call.AssertT(), handler, method, url, values, str, msgAndArgs...)
	return passed
}

// HTTPBodyNotContainsf asserts that a specified handler returns a
// body that does not contain a string.
//
//	assert.HTTPBodyNotContainsf(t, myHandler, "GET", "www.google.com", nil, "I'm Feeling Lucky", "error message %s", "formatted")
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPBodyNotContainsf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.HTTPBodyNotContainsf")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values), report.Arg("str", str))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.HTTPBodyNotContainsf(call.AssertT(), handler, method, url, values, str, msg, args...)
	return passed
}

// HTTPError asserts that a specified handler returns an error status code.
//
//	assert.HTTPError(t, myHandler, "POST", "/a/b/c", url.Values{"a": []string{"b", "c"}}
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPError(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.HTTPError")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.HTTPError(call.AssertT(), handler, method, url, values, msgAndArgs...)
	return passed
}

// HTTPErrorf asserts that a specified handler returns an error status code.
//
//	assert.HTTPErrorf(t, myHandler, "POST", "/a/b/c", url.Values{"a": []string{"b", "c"}}
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPErrorf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.HTTPErrorf")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.HTTPErrorf(call.AssertT(), handler, method, url, values, msg, args...)
	return passed
}

// HTTPRedirect asserts that a specified handler returns a redirect status code.
//
//	assert.HTTPRedirect(t, myHandler, "GET", "/a/b/c", url.Values{"a": []string{"b", "c"}}
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPRedirect(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.HTTPRedirect")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.HTTPRedirect(call.AssertT(), handler, method, url, values, msgAndArgs...)
	return passed
}

// HTTPRedirectf asserts that a specified handler returns a redirect status code.
//
//	assert.HTTPRedirectf(t, myHandler, "GET", "/a/b/c", url.Values{"a": []string{"b", "c"}}
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPRedirectf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.HTTPRedirectf")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.HTTPRedirectf(call.AssertT(), handler, method, url, values, msg, args...)
	return passed
}

// HTTPStatusCode asserts that a specified handler returns a specified status code.
//
//	assert.HTTPStatusCode(t, myHandler, "GET", "/notImplemented", nil, 501)
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPStatusCode(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, statuscode int, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.HTTPStatusCode")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values), report.Arg("statuscode", statuscode))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.HTTPStatusCode(call.AssertT(), handler, method, url, values, statuscode, msgAndArgs...)
	return passed
}

// HTTPStatusCodef asserts that a specified handler returns a specified status code.
//
//	assert.HTTPStatusCodef(t, myHandler, "GET", "/notImplemented", nil, 501, "error message %s", "formatted")
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPStatusCodef(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, statuscode int, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.HTTPStatusCodef")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values), report.Arg("statuscode", statuscode))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.HTTPStatusCodef(call.AssertT(), handler, method, url, values, statuscode, msg, args...)
	return passed
}

// HTTPSuccess asserts that a specified handler returns a success status code.
//
//	assert.HTTPSuccess(t, myHandler, "POST", "http://www.google.com", nil)
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPSuccess(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.HTTPSuccess")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.HTTPSuccess(call.AssertT(), handler, method, url, values, msgAndArgs...)
	return passed
}

// HTTPSuccessf asserts that a specified handler returns a success status code.
//
//	assert.HTTPSuccessf(t, myHandler, "POST", "http://www.google.com", nil, "error message %s", "formatted")
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPSuccessf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.HTTPSuccessf")
	call.Capture(report.Arg("handler", handler), report.Arg("method", method), report.Arg("url", url), report.Arg("values", values))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.HTTPSuccessf(call.AssertT(), handler, method, url, values, msg, args...)
	return passed
}

// Implements asserts that an object is implemented by the specified interface.
//
//	assert.Implements(t, (*MyInterface)(nil), new(MyObject))
func Implements(t TestingT, interfaceObject interface{}, object interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Implements")
	call.Capture(report.Arg("interfaceObject", interfaceObject), report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Implements(call.AssertT(), interfaceObject, object, msgAndArgs...)
	return passed
}

// Implementsf asserts that an object is implemented by the specified interface.
//
//	assert.Implementsf(t, (*MyInterface)(nil), new(MyObject), "error message %s", "formatted")
func Implementsf(t TestingT, interfaceObject interface{}, object interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Implementsf")
	call.Capture(report.Arg("interfaceObject", interfaceObject), report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Implementsf(call.AssertT(), interfaceObject, object, msg, args...)
	return passed
}

// InDelta asserts that the two numerals are within delta of each other.
//
//	assert.InDelta(t, math.Pi, 22/7.0, 0.01)
func InDelta(t TestingT, expected interface{}, actual interface{}, delta float64, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.InDelta")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.InDelta(call.AssertT(), expected, actual, delta, msgAndArgs...)
	return passed
}

// InDeltaMapValues is the same as InDelta, but it compares all values between two maps. Both maps must have exactly the same keys.
func InDeltaMapValues(t TestingT, expected interface{}, actual interface{}, delta float64, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.InDeltaMapValues")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.InDeltaMapValues(call.AssertT(), expected, actual, delta, msgAndArgs...)
	return passed
}

// InDeltaMapValuesf is the same as InDelta, but it compares all values between two maps. Both maps must have exactly the same keys.
func InDeltaMapValuesf(t TestingT, expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.InDeltaMapValuesf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.InDeltaMapValuesf(call.AssertT(), expected, actual, delta, msg, args...)
	return passed
}

// InDeltaSlice is the same as InDelta, except it compares two slices.
func InDeltaSlice(t TestingT, expected interface{}, actual interface{}, delta float64, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.InDeltaSlice")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.InDeltaSlice(call.AssertT(), expected, actual, delta, msgAndArgs...)
	return passed
}

// InDeltaSlicef is the same as InDelta, except it compares two slices.
func InDeltaSlicef(t TestingT, expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.InDeltaSlicef")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.InDeltaSlicef(call.AssertT(), expected, actual, delta, msg, args...)
	return passed
}

// InDeltaf asserts that the two numerals are within delta of each other.
//
//	assert.InDeltaf(t, math.Pi, 22/7.0, 0.01, "error message %s", "formatted")
func InDeltaf(t TestingT, expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.InDeltaf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.InDeltaf(call.AssertT(), expected, actual, delta, msg, args...)
	return passed
}

// InEpsilon asserts that expected and actual have a relative error less than epsilon
func InEpsilon(t TestingT, expected interface{}, actual interface{}, epsilon float64, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.InEpsilon")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("epsilon", epsilon))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.InEpsilon(call.AssertT(), expected, actual, epsilon, msgAndArgs...)
	return passed
}

// InEpsilonSlice is the same as InEpsilon, except it compares each value from two slices.
func InEpsilonSlice(t TestingT, expected interface{}, actual interface{}, epsilon float64, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.InEpsilonSlice")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("epsilon", epsilon))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.InEpsilonSlice(call.AssertT(), expected, actual, epsilon, msgAndArgs...)
	return passed
}

// InEpsilonSlicef is the same as InEpsilon, except it compares each value from two slices.
func InEpsilonSlicef(t TestingT, expected interface{}, actual interface{}, epsilon float64, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.InEpsilonSlicef")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("epsilon", epsilon))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.InEpsilonSlicef(call.AssertT(), expected, actual, epsilon, msg, args...)
	return passed
}

// InEpsilonf asserts that expected and actual have a relative error less than epsilon
func InEpsilonf(t TestingT, expected interface{}, actual interface{}, epsilon float64, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.InEpsilonf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("epsilon", epsilon))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.InEpsilonf(call.AssertT(), expected, actual, epsilon, msg, args...)
	return passed
}

// IsDecreasing asserts that the collection is decreasing
//
//	assert.IsDecreasing(t, []int{2, 1, 0})
//	assert.IsDecreasing(t, []float{2, 1})
//	assert.IsDecreasing(t, []string{"b", "a"})
func IsDecreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.IsDecreasing")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.IsDecreasing(call.AssertT(), object, msgAndArgs...)
	return passed
}

// IsDecreasingf asserts that the collection is decreasing
//
//	assert.IsDecreasingf(t, []int{2, 1, 0}, "error message %s", "formatted")
//	assert.IsDecreasingf(t, []float{2, 1}, "error message %s", "formatted")
//	assert.IsDecreasingf(t, []string{"b", "a"}, "error message %s", "formatted")
func IsDecreasingf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.IsDecreasingf")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.IsDecreasingf(call.AssertT(), object, msg, args...)
	return passed
}

// IsIncreasing asserts that the collection is increasing
//
//	assert.IsIncreasing(t, []int{1, 2, 3})
//	assert.IsIncreasing(t, []float{1, 2})
//	assert.IsIncreasing(t, []string{"a", "b"})
func IsIncreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.IsIncreasing")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.IsIncreasing(call.AssertT(), object, msgAndArgs...)
	return passed
}

// IsIncreasingf asserts that the collection is increasing
//
//	assert.IsIncreasingf(t, []int{1, 2, 3}, "error message %s", "formatted")
//	assert.IsIncreasingf(t, []float{1, 2}, "error message %s", "formatted")
//	assert.IsIncreasingf(t, []string{"a", "b"}, "error message %s", "formatted")
func IsIncreasingf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.IsIncreasingf")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.IsIncreasingf(call.AssertT(), object, msg, args...)
	return passed
}

// IsNonDecreasing asserts that the collection is not decreasing
//
//	assert.IsNonDecreasing(t, []int{1, 1, 2})
//	assert.IsNonDecreasing(t, []float{1, 2})
//	assert.IsNonDecreasing(t, []string{"a", "b"})
func IsNonDecreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.IsNonDecreasing")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.IsNonDecreasing(call.AssertT(), object, msgAndArgs...)
	return passed
}

// IsNonDecreasingf asserts that the collection is not decreasing
//
//	assert.IsNonDecreasingf(t, []int{1, 1, 2}, "error message %s", "formatted")
//	assert.IsNonDecreasingf(t, []float{1, 2}, "error message %s", "formatted")
//	assert.IsNonDecreasingf(t, []string{"a", "b"}, "error message %s", "formatted")
func IsNonDecreasingf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.IsNonDecreasingf")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.IsNonDecreasingf(call.AssertT(), object, msg, args...)
	return passed
}

// IsNonIncreasing asserts that the collection is not increasing
//
//	assert.IsNonIncreasing(t, []int{2, 1, 1})
//	assert.IsNonIncreasing(t, []float{2, 1})
//	assert.IsNonIncreasing(t, []string{"b", "a"})
func IsNonIncreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.IsNonIncreasing")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.IsNonIncreasing(call.AssertT(), object, msgAndArgs...)
	return passed
}

// IsNonIncreasingf asserts that the collection is not increasing
//
//	assert.IsNonIncreasingf(t, []int{2, 1, 1}, "error message %s", "formatted")
//	assert.IsNonIncreasingf(t, []float{2, 1}, "error message %s", "formatted")
//	assert.IsNonIncreasingf(t, []string{"b", "a"}, "error message %s", "formatted")
func IsNonIncreasingf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.IsNonIncreasingf")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.IsNonIncreasingf(call.AssertT(), object, msg, args...)
	return passed
}

// IsNotType asserts that the specified objects are not of the same type.
//
//	assert.IsNotType(t, &NotMyStruct{}, &MyStruct{})
func IsNotType(t TestingT, theType interface{}, object interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.IsNotType")
	call.Capture(report.Arg("theType", theType), report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.IsNotType(call.AssertT(), theType, object, msgAndArgs...)
	return passed
}

// IsNotTypef asserts that the specified objects are not of the same type.
//
//	assert.IsNotTypef(t, &NotMyStruct{}, &MyStruct{}, "error message %s", "formatted")
func IsNotTypef(t TestingT, theType interface{}, object interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.IsNotTypef")
	call.Capture(report.Arg("theType", theType), report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.IsNotTypef(call.AssertT(), theType, object, msg, args...)
	return passed
}

// IsType asserts that the specified objects are of the same type.
//
//	assert.IsType(t, &MyStruct{}, &MyStruct{})
func IsType(t TestingT, expectedType interface{}, object interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.IsType")
	call.Capture(report.Arg("expectedType", expectedType), report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.IsType(call.AssertT(), expectedType, object, msgAndArgs...)
	return passed
}

// IsTypef asserts that the specified objects are of the same type.
//
//	assert.IsTypef(t, &MyStruct{}, &MyStruct{}, "error message %s", "formatted")
func IsTypef(t TestingT, expectedType interface{}, object interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.IsTypef")
	call.Capture(report.Arg("expectedType", expectedType), report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.IsTypef(call.AssertT(), expectedType, object, msg, args...)
	return passed
}

// JSONEq asserts that two JSON strings are equivalent.
//
//	assert.JSONEq(t, `{"hello": "world", "foo": "bar"}`, `{"foo": "bar", "hello": "world"}`)
func JSONEq(t TestingT, expected string, actual string, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.JSONEq")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.JSONEq(call.AssertT(), expected, actual, msgAndArgs...)
	return passed
}

// JSONEqf asserts that two JSON strings are equivalent.
//
//	assert.JSONEqf(t, `{"hello": "world", "foo": "bar"}`, `{"foo": "bar", "hello": "world"}`, "error message %s", "formatted")
func JSONEqf(t TestingT, expected string, actual string, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.JSONEqf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.JSONEqf(call.AssertT(), expected, actual, msg, args...)
	return passed
}

// Len asserts that the specified object has specific length.
// Len also fails if the object has a type that len() not accept.
//
//	assert.Len(t, mySlice, 3)
func Len(t TestingT, object interface{}, length int, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Len")
	call.Capture(report.Arg("object", object), report.Arg("length", length))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Len(call.AssertT(), object, length, msgAndArgs...)
	return passed
}

// Lenf asserts that the specified object has specific length.
// Lenf also fails if the object has a type that len() not accept.
//
//	assert.Lenf(t, mySlice, 3, "error message %s", "formatted")
func Lenf(t TestingT, object interface{}, length int, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Lenf")
	call.Capture(report.Arg("object", object), report.Arg("length", length))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Lenf(call.AssertT(), object, length, msg, args...)
	return passed
}

// Less asserts that the first element is less than the second
//
//	assert.Less(t, 1, 2)
//	assert.Less(t, float64(1), float64(2))
//	assert.Less(t, "a", "b")
func Less(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Less")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Less(call.AssertT(), e1, e2, msgAndArgs...)
	return passed
}

// LessOrEqual asserts that the first element is less than or equal to the second
//
//	assert.LessOrEqual(t, 1, 2)
//	assert.LessOrEqual(t, 2, 2)
//	assert.LessOrEqual(t, "a", "b")
//	assert.LessOrEqual(t, "b", "b")
func LessOrEqual(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.LessOrEqual")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.LessOrEqual(call.AssertT(), e1, e2, msgAndArgs...)
	return passed
}

// LessOrEqualf asserts that the first element is less than or equal to the second
//
//	assert.LessOrEqualf(t, 1, 2, "error message %s", "formatted")
//	assert.LessOrEqualf(t, 2, 2, "error message %s", "formatted")
//	assert.LessOrEqualf(t, "a", "b", "error message %s", "formatted")
//	assert.LessOrEqualf(t, "b", "b", "error message %s", "formatted")
func LessOrEqualf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.LessOrEqualf")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.LessOrEqualf(call.AssertT(), e1, e2, msg, args...)
	return passed
}

// Lessf asserts that the first element is less than the second
//
//	assert.Lessf(t, 1, 2, "error message %s", "formatted")
//	assert.Lessf(t, float64(1), float64(2), "error message %s", "formatted")
//	assert.Lessf(t, "a", "b", "error message %s", "formatted")
func Lessf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Lessf")
	call.Capture(report.Arg("e1", e1), report.Arg("e2", e2))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Lessf(call.AssertT(), e1, e2, msg, args...)
	return passed
}

// Negative asserts that the specified element is negative
//
//	assert.Negative(t, -1)
//	assert.Negative(t, -1.23)
func Negative(t TestingT, e interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Negative")
	call.Capture(report.Arg("e", e))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Negative(call.AssertT(), e, msgAndArgs...)
	return passed
}

// Negativef asserts that the specified element is negative
//
//	assert.Negativef(t, -1, "error message %s", "formatted")
//	assert.Negativef(t, -1.23, "error message %s", "formatted")
func Negativef(t TestingT, e interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Negativef")
	call.Capture(report.Arg("e", e))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Negativef(call.AssertT(), e, msg, args...)
	return passed
}

// Never asserts that the given condition doesn't satisfy in waitFor time,
// periodically checking the target function each tick.
//
//	assert.Never(t, func() bool { return false; }, time.Second, 10*time.Millisecond)
func Never(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Never")
	call.Capture(report.Arg("condition", condition), report.Arg("waitFor", waitFor), report.Arg("tick", tick))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Never(call.AssertT(), condition, waitFor, tick, msgAndArgs...)
	return passed
}

// Neverf asserts that the given condition doesn't satisfy in waitFor time,
// periodically checking the target function each tick.
//
//	assert.Neverf(t, func() bool { return false; }, time.Second, 10*time.Millisecond, "error message %s", "formatted")
func Neverf(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Neverf")
	call.Capture(report.Arg("condition", condition), report.Arg("waitFor", waitFor), report.Arg("tick", tick))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Neverf(call.AssertT(), condition, waitFor, tick, msg, args...)
	return passed
}

// Nil asserts that the specified object is nil.
//
//	assert.Nil(t, err)
func Nil(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Nil")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Nil(call.AssertT(), object, msgAndArgs...)
	return passed
}

// Nilf asserts that the specified object is nil.
//
//	assert.Nilf(t, err, "error message %s", "formatted")
func Nilf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Nilf")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Nilf(call.AssertT(), object, msg, args...)
	return passed
}

// NoDirExists checks whether a directory does not exist in the given path.
// It fails if the path points to an existing _directory_ only.
func NoDirExists(t TestingT, path string, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NoDirExists")
	call.Capture(report.Arg("path", path))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NoDirExists(call.AssertT(), path, msgAndArgs...)
	return passed
}

// NoDirExistsf checks whether a directory does not exist in the given path.
// It fails if the path points to an existing _directory_ only.
func NoDirExistsf(t TestingT, path string, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NoDirExistsf")
	call.Capture(report.Arg("path", path))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NoDirExistsf(call.AssertT(), path, msg, args...)
	return passed
}

// NoError asserts that a function returned no error (i.e. `nil`).
//
//	  actualObj, err := SomeFunction()
//	  if assert.NoError(t, err) {
//		   assert.Equal(t, expectedObj, actualObj)
//	  }
func NoError(t TestingT, err error, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NoError")
	call.Capture(report.Arg("err", err))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NoError(call.AssertT(), err, msgAndArgs...)
	return passed
}

// NoErrorf asserts that a function returned no error (i.e. `nil`).
//
//	  actualObj, err := SomeFunction()
//	  if assert.NoErrorf(t, err, "error message %s", "formatted") {
//		   assert.Equal(t, expectedObj, actualObj)
//	  }
func NoErrorf(t TestingT, err error, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NoErrorf")
	call.Capture(report.Arg("err", err))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NoErrorf(call.AssertT(), err, msg, args...)
	return passed
}

// NoFileExists checks whether a file does not exist in a given path. It fails
// if the path points to an existing _file_ only.
func NoFileExists(t TestingT, path string, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NoFileExists")
	call.Capture(report.Arg("path", path))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NoFileExists(call.AssertT(), path, msgAndArgs...)
	return passed
}

// NoFileExistsf checks whether a file does not exist in a given path. It fails
// if the path points to an existing _file_ only.
func NoFileExistsf(t TestingT, path string, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NoFileExistsf")
	call.Capture(report.Arg("path", path))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NoFileExistsf(call.AssertT(), path, msg, args...)
	return passed
}

// NotContains asserts that the specified string, list(array, slice...) or map does NOT contain the
// specified substring or element.
//
//	assert.NotContains(t, "Hello World", "Earth")
//	assert.NotContains(t, ["Hello", "World"], "Earth")
//	assert.NotContains(t, {"Hello": "World"}, "Earth")
func NotContains(t TestingT, s interface{}, contains interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NotContains")
	call.Capture(report.Arg("s", s), report.Arg("contains", contains))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotContains(call.AssertT(), s, contains, msgAndArgs...)
	return passed
}

// NotContainsf asserts that the specified string, list(array, slice...) or map does NOT contain the
// specified substring or element.
//
//	assert.NotContainsf(t, "Hello World", "Earth", "error message %s", "formatted")
//	assert.NotContainsf(t, ["Hello", "World"], "Earth", "error message %s", "formatted")
//	assert.NotContainsf(t, {"Hello": "World"}, "Earth", "error message %s", "formatted")
func NotContainsf(t TestingT, s interface{}, contains interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NotContainsf")
	call.Capture(report.Arg("s", s), report.Arg("contains", contains))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotContainsf(call.AssertT(), s, contains, msg, args...)
	return passed
}

// NotElementsMatch asserts that the specified listA(array, slice...) is NOT equal to specified
// listB(array, slice...) ignoring the order of the elements. If there are duplicate elements,
// the number of appearances of each of them in both lists should not match.
// This is an inverse of ElementsMatch.
//
// assert.NotElementsMatch(t, [1, 1, 2, 3], [1, 1, 2, 3]) -> false
//
// assert.NotElementsMatch(t, [1, 1, 2, 3], [1, 2, 3]) -> true
//
// assert.NotElementsMatch(t, [1, 2, 3], [1, 2, 4]) -> true
func NotElementsMatch(t TestingT, listA interface{}, listB interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NotElementsMatch")
	call.Capture(report.Arg("listA", listA), report.Arg("listB", listB))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotElementsMatch(call.AssertT(), listA, listB, msgAndArgs...)
	return passed
}

// NotElementsMatchf asserts that the specified listA(array, slice...) is NOT equal to specified
// listB(array, slice...) ignoring the order of the elements. If there are duplicate elements,
// the number of appearances of each of them in both lists should not match.
// This is an inverse of ElementsMatch.
//
// assert.NotElementsMatchf(t, [1, 1, 2, 3], [1, 1, 2, 3], "error message %s", "formatted") -> false
//
// assert.NotElementsMatchf(t, [1, 1, 2, 3], [1, 2, 3], "error message %s", "formatted") -> true
//
// assert.NotElementsMatchf(t, [1, 2, 3], [1, 2, 4], "error message %s", "formatted") -> true
func NotElementsMatchf(t TestingT, listA interface{}, listB interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NotElementsMatchf")
	call.Capture(report.Arg("listA", listA), report.Arg("listB", listB))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotElementsMatchf(call.AssertT(), listA, listB, msg, args...)
	return passed
}

// NotEmpty asserts that the specified object is NOT [Empty].
//
//	if assert.NotEmpty(t, obj) {
//	  assert.Equal(t, "two", obj[1])
//	}
func NotEmpty(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NotEmpty")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotEmpty(call.AssertT(), object, msgAndArgs...)
	return passed
}

// NotEmptyf asserts that the specified object is NOT [Empty].
//
//	if assert.NotEmptyf(t, obj, "error message %s", "formatted") {
//	  assert.Equal(t, "two", obj[1])
//	}
func NotEmptyf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NotEmptyf")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotEmptyf(call.AssertT(), object, msg, args...)
	return passed
}

// NotEqual asserts that the specified values are NOT equal.
//
//	assert.NotEqual(t, obj1, obj2)
//
// Pointer variable equality is determined based on the equality of the
// referenced values (as opposed to the memory addresses).
func NotEqual(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NotEqual")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotEqual(call.AssertT(), expected, actual, msgAndArgs...)
	return passed
}

// NotEqualValues asserts that two objects are not equal even when converted to the same type
//
//	assert.NotEqualValues(t, obj1, obj2)
func NotEqualValues(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NotEqualValues")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotEqualValues(call.AssertT(), expected, actual, msgAndArgs...)
	return passed
}

// NotEqualValuesf asserts that two objects are not equal even when converted to the same type
//
//	assert.NotEqualValuesf(t, obj1, obj2, "error message %s", "formatted")
func NotEqualValuesf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NotEqualValuesf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotEqualValuesf(call.AssertT(), expected, actual, msg, args...)
	return passed
}

// NotEqualf asserts that the specified values are NOT equal.
//
//	assert.NotEqualf(t, obj1, obj2, "error message %s", "formatted")
//
// Pointer variable equality is determined based on the equality of the
// referenced values (as opposed to the memory addresses).
func NotEqualf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NotEqualf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotEqualf(call.AssertT(), expected, actual, msg, args...)
	return passed
}

// NotErrorAs asserts that none of the errors in err's chain matches target,
// but if so, sets target to that error value.
func NotErrorAs(t TestingT, err error, target interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NotErrorAs")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotErrorAs(call.AssertT(), err, target, msgAndArgs...)
	return passed
}

// NotErrorAsf asserts that none of the errors in err's chain matches target,
// but if so, sets target to that error value.
func NotErrorAsf(t TestingT, err error, target interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NotErrorAsf")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotErrorAsf(call.AssertT(), err, target, msg, args...)
	return passed
}

// NotErrorIs asserts that none of the errors in err's chain matches target.
// This is a wrapper for errors.Is.
func NotErrorIs(t TestingT, err error, target error, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NotErrorIs")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotErrorIs(call.AssertT(), err, target, msgAndArgs...)
	return passed
}

// NotErrorIsf asserts that none of the errors in err's chain matches target.
// This is a wrapper for errors.Is.
func NotErrorIsf(t TestingT, err error, target error, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NotErrorIsf")
	call.Capture(report.Arg("err", err), report.Arg("target", target))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotErrorIsf(call.AssertT(), err, target, msg, args...)
	return passed
}

// NotImplements asserts that an object does not implement the specified interface.
//
//	assert.NotImplements(t, (*MyInterface)(nil), new(MyObject))
func NotImplements(t TestingT, interfaceObject interface{}, object interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NotImplements")
	call.Capture(report.Arg("interfaceObject", interfaceObject), report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotImplements(call.AssertT(), interfaceObject, object, msgAndArgs...)
	return passed
}

// NotImplementsf asserts that an object does not implement the specified interface.
//
//	assert.NotImplementsf(t, (*MyInterface)(nil), new(MyObject), "error message %s", "formatted")
func NotImplementsf(t TestingT, interfaceObject interface{}, object interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NotImplementsf")
	call.Capture(report.Arg("interfaceObject", interfaceObject), report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotImplementsf(call.AssertT(), interfaceObject, object, msg, args...)
	return passed
}

// NotNil asserts that the specified object is not nil.
//
//	assert.NotNil(t, err)
func NotNil(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NotNil")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotNil(call.AssertT(), object, msgAndArgs...)
	return passed
}

// NotNilf asserts that the specified object is not nil.
//
//	assert.NotNilf(t, err, "error message %s", "formatted")
func NotNilf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NotNilf")
	call.Capture(report.Arg("object", object))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotNilf(call.AssertT(), object, msg, args...)
	return passed
}

// NotPanics asserts that the code inside the specified PanicTestFunc does NOT panic.
//
//	assert.NotPanics(t, func(){ RemainCalm() })
func NotPanics(t TestingT, f PanicTestFunc, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NotPanics")
	call.Capture(report.Arg("f", f))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotPanics(call.AssertT(), f, msgAndArgs...)
	return passed
}

// NotPanicsf asserts that the code inside the specified PanicTestFunc does NOT panic.
//
//	assert.NotPanicsf(t, func(){ RemainCalm() }, "error message %s", "formatted")
func NotPanicsf(t TestingT, f PanicTestFunc, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NotPanicsf")
	call.Capture(report.Arg("f", f))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotPanicsf(call.AssertT(), f, msg, args...)
	return passed
}

// NotRegexp asserts that a specified regexp does not match a string.
//
//	assert.NotRegexp(t, regexp.MustCompile("starts"), "it's starting")
//	assert.NotRegexp(t, "^start", "it's not starting")
func NotRegexp(t TestingT, rx interface{}, str interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NotRegexp")
	call.Capture(report.Arg("rx", rx), report.Arg("str", str))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotRegexp(call.AssertT(), rx, str, msgAndArgs...)
	return passed
}

// NotRegexpf asserts that a specified regexp does not match a string.
//
//	assert.NotRegexpf(t, regexp.MustCompile("starts"), "it's starting", "error message %s", "formatted")
//	assert.NotRegexpf(t, "^start", "it's not starting", "error message %s", "formatted")
func NotRegexpf(t TestingT, rx interface{}, str interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NotRegexpf")
	call.Capture(report.Arg("rx", rx), report.Arg("str", str))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotRegexpf(call.AssertT(), rx, str, msg, args...)
	return passed
}

// NotSame asserts that two pointers do not reference the same object.
//
//	assert.NotSame(t, ptr1, ptr2)
//
// Both arguments must be pointer variables. Pointer variable sameness is
// determined based on the equality of both type and value.
func NotSame(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NotSame")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotSame(call.AssertT(), expected, actual, msgAndArgs...)
	return passed
}

// NotSamef asserts that two pointers do not reference the same object.
//
//	assert.NotSamef(t, ptr1, ptr2, "error message %s", "formatted")
//
// Both arguments must be pointer variables. Pointer variable sameness is
// determined based on the equality of both type and value.
func NotSamef(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NotSamef")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotSamef(call.AssertT(), expected, actual, msg, args...)
	return passed
}

// NotSubset asserts that the list (array, slice, or map) does NOT contain all
// elements given in the subset (array, slice, or map).
// Map elements are key-value pairs unless compared with an array or slice where
// only the map key is evaluated.
//
//	assert.NotSubset(t, [1, 3, 4], [1, 2])
//	assert.NotSubset(t, {"x": 1, "y": 2}, {"z": 3})
//	assert.NotSubset(t, [1, 3, 4], {1: "one", 2: "two"})
//	assert.NotSubset(t, {"x": 1, "y": 2}, ["z"])
func NotSubset(t TestingT, list interface{}, subset interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NotSubset")
	call.Capture(report.Arg("list", list), report.Arg("subset", subset))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotSubset(call.AssertT(), list, subset, msgAndArgs...)
	return passed
}

// NotSubsetf asserts that the list (array, slice, or map) does NOT contain all
// elements given in the subset (array, slice, or map).
// Map elements are key-value pairs unless compared with an array or slice where
// only the map key is evaluated.
//
//	assert.NotSubsetf(t, [1, 3, 4], [1, 2], "error message %s", "formatted")
//	assert.NotSubsetf(t, {"x": 1, "y": 2}, {"z": 3}, "error message %s", "formatted")
//	assert.NotSubsetf(t, [1, 3, 4], {1: "one", 2: "two"}, "error message %s", "formatted")
//	assert.NotSubsetf(t, {"x": 1, "y": 2}, ["z"], "error message %s", "formatted")
func NotSubsetf(t TestingT, list interface{}, subset interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NotSubsetf")
	call.Capture(report.Arg("list", list), report.Arg("subset", subset))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotSubsetf(call.AssertT(), list, subset, msg, args...)
	return passed
}

// NotZero asserts that i is not the zero value for its type.
func NotZero(t TestingT, i interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.NotZero")
	call.Capture(report.Arg("i", i))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotZero(call.AssertT(), i, msgAndArgs...)
	return passed
}

// NotZerof asserts that i is not the zero value for its type.
func NotZerof(t TestingT, i interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.NotZerof")
	call.Capture(report.Arg("i", i))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.NotZerof(call.AssertT(), i, msg, args...)
	return passed
}

// ObjectsAreEqual determines if two objects are considered equal.
//
// This function does no assertion of any kind.
func ObjectsAreEqual(expected interface{}, actual interface{}) bool {
	return upstream.ObjectsAreEqual(expected, actual)
}

// ObjectsAreEqualValues gets whether two objects are equal, or if their
// values are equal.
func ObjectsAreEqualValues(expected interface{}, actual interface{}) bool {
	return upstream.ObjectsAreEqualValues(expected, actual)
}

// ObjectsExportedFieldsAreEqual determines if the exported (public) fields of two objects are
// considered equal. This comparison of only exported fields is applied recursively to nested data
// structures.
//
// This function does no assertion of any kind.
//
// Deprecated: Use [EqualExportedValues] instead.
func ObjectsExportedFieldsAreEqual(expected interface{}, actual interface{}) bool {
	return upstream.ObjectsExportedFieldsAreEqual(expected, actual)
}

// Panics asserts that the code inside the specified PanicTestFunc panics.
//
//	assert.Panics(t, func(){ GoCrazy() })
func Panics(t TestingT, f PanicTestFunc, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Panics")
	call.Capture(report.Arg("f", f))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Panics(call.AssertT(), f, msgAndArgs...)
	return passed
}

// PanicsWithError asserts that the code inside the specified PanicTestFunc
// panics, and that the recovered panic value is an error that satisfies the
// EqualError comparison.
//
//	assert.PanicsWithError(t, "crazy error", func(){ GoCrazy() })
func PanicsWithError(t TestingT, errString string, f PanicTestFunc, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.PanicsWithError")
	call.Capture(report.Arg("errString", errString), report.Arg("f", f))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.PanicsWithError(call.AssertT(), errString, f, msgAndArgs...)
	return passed
}

// PanicsWithErrorf asserts that the code inside the specified PanicTestFunc
// panics, and that the recovered panic value is an error that satisfies the
// EqualError comparison.
//
//	assert.PanicsWithErrorf(t, "crazy error", func(){ GoCrazy() }, "error message %s", "formatted")
func PanicsWithErrorf(t TestingT, errString string, f PanicTestFunc, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.PanicsWithErrorf")
	call.Capture(report.Arg("errString", errString), report.Arg("f", f))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.PanicsWithErrorf(call.AssertT(), errString, f, msg, args...)
	return passed
}

// PanicsWithValue asserts that the code inside the specified PanicTestFunc panics, and that
// the recovered panic value equals the expected panic value.
//
//	assert.PanicsWithValue(t, "crazy error", func(){ GoCrazy() })
func PanicsWithValue(t TestingT, expected interface{}, f PanicTestFunc, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.PanicsWithValue")
	call.Capture(report.Arg("expected", expected), report.Arg("f", f))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.PanicsWithValue(call.AssertT(), expected, f, msgAndArgs...)
	return passed
}

// PanicsWithValuef asserts that the code inside the specified PanicTestFunc panics, and that
// the recovered panic value equals the expected panic value.
//
//	assert.PanicsWithValuef(t, "crazy error", func(){ GoCrazy() }, "error message %s", "formatted")
func PanicsWithValuef(t TestingT, expected interface{}, f PanicTestFunc, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.PanicsWithValuef")
	call.Capture(report.Arg("expected", expected), report.Arg("f", f))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.PanicsWithValuef(call.AssertT(), expected, f, msg, args...)
	return passed
}

// Panicsf asserts that the code inside the specified PanicTestFunc panics.
//
//	assert.Panicsf(t, func(){ GoCrazy() }, "error message %s", "formatted")
func Panicsf(t TestingT, f PanicTestFunc, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Panicsf")
	call.Capture(report.Arg("f", f))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Panicsf(call.AssertT(), f, msg, args...)
	return passed
}

// Positive asserts that the specified element is positive
//
//	assert.Positive(t, 1)
//	assert.Positive(t, 1.23)
func Positive(t TestingT, e interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Positive")
	call.Capture(report.Arg("e", e))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Positive(call.AssertT(), e, msgAndArgs...)
	return passed
}

// Positivef asserts that the specified element is positive
//
//	assert.Positivef(t, 1, "error message %s", "formatted")
//	assert.Positivef(t, 1.23, "error message %s", "formatted")
func Positivef(t TestingT, e interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Positivef")
	call.Capture(report.Arg("e", e))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Positivef(call.AssertT(), e, msg, args...)
	return passed
}

// Regexp asserts that a specified regexp matches a string.
//
//	assert.Regexp(t, regexp.MustCompile("start"), "it's starting")
//	assert.Regexp(t, "start...$", "it's not starting")
func Regexp(t TestingT, rx interface{}, str interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Regexp")
	call.Capture(report.Arg("rx", rx), report.Arg("str", str))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Regexp(call.AssertT(), rx, str, msgAndArgs...)
	return passed
}

// Regexpf asserts that a specified regexp matches a string.
//
//	assert.Regexpf(t, regexp.MustCompile("start"), "it's starting", "error message %s", "formatted")
//	assert.Regexpf(t, "start...$", "it's not starting", "error message %s", "formatted")
func Regexpf(t TestingT, rx interface{}, str interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Regexpf")
	call.Capture(report.Arg("rx", rx), report.Arg("str", str))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Regexpf(call.AssertT(), rx, str, msg, args...)
	return passed
}

// Same asserts that two pointers reference the same object.
//
//	assert.Same(t, ptr1, ptr2)
//
// Both arguments must be pointer variables. Pointer variable sameness is
// determined based on the equality of both type and value.
func Same(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Same")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Same(call.AssertT(), expected, actual, msgAndArgs...)
	return passed
}

// Samef asserts that two pointers reference the same object.
//
//	assert.Samef(t, ptr1, ptr2, "error message %s", "formatted")
//
// Both arguments must be pointer variables. Pointer variable sameness is
// determined based on the equality of both type and value.
func Samef(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Samef")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Samef(call.AssertT(), expected, actual, msg, args...)
	return passed
}

// Subset asserts that the list (array, slice, or map) contains all elements
// given in the subset (array, slice, or map).
// Map elements are key-value pairs unless compared with an array or slice where
// only the map key is evaluated.
//
//	assert.Subset(t, [1, 2, 3], [1, 2])
//	assert.Subset(t, {"x": 1, "y": 2}, {"x": 1})
//	assert.Subset(t, [1, 2, 3], {1: "one", 2: "two"})
//	assert.Subset(t, {"x": 1, "y": 2}, ["x"])
func Subset(t TestingT, list interface{}, subset interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Subset")
	call.Capture(report.Arg("list", list), report.Arg("subset", subset))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Subset(call.AssertT(), list, subset, msgAndArgs...)
	return passed
}

// Subsetf asserts that the list (array, slice, or map) contains all elements
// given in the subset (array, slice, or map).
// Map elements are key-value pairs unless compared with an array or slice where
// only the map key is evaluated.
//
//	assert.Subsetf(t, [1, 2, 3], [1, 2], "error message %s", "formatted")
//	assert.Subsetf(t, {"x": 1, "y": 2}, {"x": 1}, "error message %s", "formatted")
//	assert.Subsetf(t, [1, 2, 3], {1: "one", 2: "two"}, "error message %s", "formatted")
//	assert.Subsetf(t, {"x": 1, "y": 2}, ["x"], "error message %s", "formatted")
func Subsetf(t TestingT, list interface{}, subset interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Subsetf")
	call.Capture(report.Arg("list", list), report.Arg("subset", subset))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Subsetf(call.AssertT(), list, subset, msg, args...)
	return passed
}

// True asserts that the specified value is true.
//
//	assert.True(t, myBool)
func True(t TestingT, value bool, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.True")
	call.Capture(report.Arg("value", value))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.True(call.AssertT(), value, msgAndArgs...)
	return passed
}

// Truef asserts that the specified value is true.
//
//	assert.Truef(t, myBool, "error message %s", "formatted")
func Truef(t TestingT, value bool, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Truef")
	call.Capture(report.Arg("value", value))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Truef(call.AssertT(), value, msg, args...)
	return passed
}

// WithinDuration asserts that the two times are within duration delta of each other.
//
//	assert.WithinDuration(t, time.Now(), time.Now(), 10*time.Second)
func WithinDuration(t TestingT, expected time.Time, actual time.Time, delta time.Duration, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.WithinDuration")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.WithinDuration(call.AssertT(), expected, actual, delta, msgAndArgs...)
	return passed
}

// WithinDurationf asserts that the two times are within duration delta of each other.
//
//	assert.WithinDurationf(t, time.Now(), time.Now(), 10*time.Second, "error message %s", "formatted")
func WithinDurationf(t TestingT, expected time.Time, actual time.Time, delta time.Duration, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.WithinDurationf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual), report.Arg("delta", delta))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.WithinDurationf(call.AssertT(), expected, actual, delta, msg, args...)
	return passed
}

// WithinRange asserts that a time is within a time range (inclusive).
//
//	assert.WithinRange(t, time.Now(), time.Now().Add(-time.Second), time.Now().Add(time.Second))
func WithinRange(t TestingT, actual time.Time, start time.Time, end time.Time, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.WithinRange")
	call.Capture(report.Arg("actual", actual), report.Arg("start", start), report.Arg("end", end))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.WithinRange(call.AssertT(), actual, start, end, msgAndArgs...)
	return passed
}

// WithinRangef asserts that a time is within a time range (inclusive).
//
//	assert.WithinRangef(t, time.Now(), time.Now().Add(-time.Second), time.Now().Add(time.Second), "error message %s", "formatted")
func WithinRangef(t TestingT, actual time.Time, start time.Time, end time.Time, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.WithinRangef")
	call.Capture(report.Arg("actual", actual), report.Arg("start", start), report.Arg("end", end))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.WithinRangef(call.AssertT(), actual, start, end, msg, args...)
	return passed
}

// YAMLEq asserts that two YAML strings are equivalent.
func YAMLEq(t TestingT, expected string, actual string, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.YAMLEq")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.YAMLEq(call.AssertT(), expected, actual, msgAndArgs...)
	return passed
}

// YAMLEqf asserts that two YAML strings are equivalent.
func YAMLEqf(t TestingT, expected string, actual string, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.YAMLEqf")
	call.Capture(report.Arg("expected", expected), report.Arg("actual", actual))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.YAMLEqf(call.AssertT(), expected, actual, msg, args...)
	return passed
}

// Zero asserts that i is the zero value for its type.
func Zero(t TestingT, i interface{}, msgAndArgs ...interface{}) bool {
	call := report.Begin(t, "assert.Zero")
	call.Capture(report.Arg("i", i))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Zero(call.AssertT(), i, msgAndArgs...)
	return passed
}

// Zerof asserts that i is the zero value for its type.
func Zerof(t TestingT, i interface{}, msg string, args ...interface{}) bool {
	call := report.Begin(t, "assert.Zerof")
	call.Capture(report.Arg("i", i))
	var passed bool
	defer call.FinishAssert(&passed)
	passed = upstream.Zerof(call.AssertT(), i, msg, args...)
	return passed
}
